ministryofjustice/hmpps-probation-integration-services

- .github/workflows/build-test-deploy.yml
- .github/workflows/security.yml
- README.md
This runs every weekday morning against the latest image for each project, and uploads the results to GitHub's [security page](https://github.com/ministryofjustice/hmpps-probation-integration-services/security/code-scanning).  Security alerts will appear in the repository as configured in the [GitHub settings](https://github.com/ministryofjustice/hmpps-probation-integration-services/settings/security_analysis).
> PI-276 Add scheduled Trivy image scan

- .github/workflows/main.yml
- projects/prison-case-notes-to-probation/deploy/values-dev.yml
- projects/prison-case-notes-to-probation/deploy/values-preprod.yml
* Fix URLs for prison case notes service
* Update pre-prod to preprod, to remain consistent with MOJ CP and to prevent Jira from classifying the environment as production (see: https://github.com/atlassian/github-for-jira/blob/main/src/transforms/transform-deployment.ts#L126)
> Fix URLs for prison case notes service

- projects/prison-case-notes-to-probation/src/dev/kotlin/uk/gov/justice/digital/hmpps/ResourceLoader.kt
- projects/prison-case-notes-to-probation/src/dev/kotlin/uk/gov/justice/digital/hmpps/data/SimulationBuilder.kt
- projects/prison-case-notes-to-probation/src/dev/kotlin/uk/gov/justice/digital/hmpps/data/generator/CaseNoteMessageGenerator.kt
- projects/prison-case-notes-to-probation/src/dev/resources/messages/case-note-not-found.json
- projects/prison-case-notes-to-probation/src/dev/resources/simulations/get-case-note.json
- projects/prison-case-notes-to-probation/src/main/kotlin/uk/gov/justice/digital/hmpps/integrations/prison/PrisonCaseNote.kt
- projects/prison-case-notes-to-probation/src/main/kotlin/uk/gov/justice/digital/hmpps/integrations/prison/PrisonCaseNotesClient.kt
- projects/prison-case-notes-to-probation/src/main/kotlin/uk/gov/justice/digital/hmpps/listener/CaseNoteConverter.kt
- projects/prison-case-notes-to-probation/src/main/kotlin/uk/gov/justice/digital/hmpps/listener/MessageListener.kt
- projects/prison-case-notes-to-probation/src/main/resources/application.yml
- projects/prison-case-notes-to-probation/src/test/kotlin/uk/gov/justice/digital/hmpps/listener/MessageListenerTest.kt
renamed case note message to be prison offender event since the events may not always have case note ids
updated message listener to accept null case note id
update prison case note client to not return nullable case note
> updated message listener

- .github/workflows/deploy.yml
- README.md
- projects/prison-case-notes-to-probation/deploy/database/access.yml
- projects/prison-case-notes-to-probation/deploy/values-dev.yml
- projects/prison-case-notes-to-probation/deploy/values.yml
The deploy action now starts an SSM automation runbook in the background before deploying the service, which runs a SQL script for creating a DB account for access, and a user record for auditing.
The runbook and scripts are defined here: https://github.com/ministryofjustice/hmpps-delius-pipelines/pull/476
And the permissions to run it from CI is here: https://github.com/ministryofjustice/hmpps-security-access-terraform/pull/637
> PI-265 Add database access and audit details per-project

- .github/workflows/main.yml
This now works as the dependencies have been installed in the runner image: https://github.com/ministryofjustice/browser-testing-github-actions-runner
> PI-340 Install browsers using Playwright

- .github/actions/build-and-test/action.yml
- .github/workflows/deploy.yml
Forked PRs are read-only, so the test reporter is unable to create the checks
> Don't publish test reports from forked PRs

- libs/commons/src/main/kotlin/uk/gov/justice/digital/hmpps/message/HmppsEvent.kt
- libs/commons/src/main/kotlin/uk/gov/justice/digital/hmpps/telemetry/TelemetryService.kt
- libs/dev-tools/src/main/kotlin/uk/gov/justice/digital/hmpps/TestHelper.kt
- projects/pre-sentence-reports-to-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/listener/MessageListener.kt
- projects/workforce-allocations-to-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/listener/MessageListener.kt
The release and recall messages don't specify a detailUrl - all the information is in the message.  I expect it'll be the same for the RSR score messages too.
> Updated HmppsEvent to make detailUrl optional

- projects/person-search-index-from-delius/container/Dockerfile
- projects/person-search-index-from-delius/container/logstash-full-load-dlq.conf
- projects/person-search-index-from-delius/container/logstash-full-load.conf
- projects/person-search-index-from-delius/container/logstash-incremental-dlq.conf
- projects/person-search-index-from-delius/container/logstash-incremental.conf
- projects/person-search-index-from-delius/container/logstash.yml
- projects/person-search-index-from-delius/container/pipelines.yml
- projects/person-search-index-from-delius/deploy/values.yml
- projects/person-search-index-from-delius/docker-compose.yml
This commit updates the Logstash pipelines to handle two main types of failures:
1. failures in the `filter` plugins (e.g. JSON parsing)
2. failures in the `output` plugins (e.g. non-retryable error responses from Elasticsearch/OpenSearch)
Note that failures in the `input` plugins will result in the pipeline being terminated.
Typically, filters add "tags" to the event when an error occurs - rather than actually failing or dropping the event. This is problematic as we could accidentally index partial/invalid documents, if for example the JDBC lookup fails in the incremental pipeline.
This is now handled by checking for the presence of tags and sending the message to the SQS DLQ.
The `elasticsearch`/`opensearch` output plugins will retry most errors indefinitely, however 400 and 404 errors …
> PI-406 Send failed Logstash events to the SQS DLQ

- projects/person-search-index-from-delius/container/logstash-incremental.conf
This prevents any previous errors from being detected and re-sent to the DLQ.
> PI-424 Remove tags at start of incremental pipeline

- .github/dependabot.yml
Dependabot doesn't support wildcards or searching through subdirectories, so for now we'll have to specify any Dockerfiles manually.  See https://github.com/dependabot/dependabot-core/issues/2178
> Specify Dockerfile location for Dependabot

- projects/prison-custody-status-to-delius/src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/PrisonCustodyStatusToDeliusIntegrationTest.kt
- projects/prison-custody-status-to-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/integrations/delius/custody/Custody.kt
- projects/prison-custody-status-to-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/listener/MessageListener.kt
- projects/prison-custody-status-to-delius/src/test/kotlin/uk/gov/justice/hmpps/listener/MessageListenerTest.kt
This otherwise causes validation to fail in Delius when adding licence conditions.
Also adds missing audit fields to the Custody entity.
> PI-428 Remove time component from release/recall dates

- .github/workflows/bootstrap.yml
- templates/service-with-load-balancer.tf
This adds an extra toggle to the bootstrap workflow: 
> **Will the service provide a HTTP API that requires access from MOJ Cloud Platform?**
When enabled, the bootstrap workflow will automatically add a load balancer to the Terraform code.  It's off-by-default, as most of our services so far are message listeners, rather than API providers.
> PI-434 Update bootstrap to optionally create a load balancer for API ingress

- templates/projects/message-listener/deploy/values-dev.yml
- templates/projects/message-listener/deploy/values-preprod.yml
- templates/projects/message-listener/deploy/values-prod.yml
There is no OAuth or API client configuration in this template, so the HMPPS Auth urls are not required
> Remove auth config from message-listener template

- projects/prison-custody-status-to-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/integrations/delius/recall/RecallService.kt
- projects/prison-custody-status-to-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/integrations/delius/release/ReleaseService.kt
- projects/prison-custody-status-to-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/listener/MessageListener.kt
- projects/prison-custody-status-to-delius/src/test/kotlin/uk/gov/justice/digital/hmpps/integrations/delius/recall/RecallServiceTest.kt
- projects/prison-custody-status-to-delius/src/test/kotlin/uk/gov/justice/digital/hmpps/integrations/delius/release/ReleaseServiceTest.kt
- projects/prison-custody-status-to-delius/src/test/kotlin/uk/gov/justice/hmpps/listener/MessageListenerTest.kt
Previously only the truncated date was being recorded, which can cause the check for a currently active responsible officer to fail.
This maintains the truncated date on the release/recall/custody/licence records, so there should be no impact on Delius functionality.
> PI-451 Include timestamp for allocations and contacts

- .github/dependabot.yml
- .github/workflows/tools.yml
- buildSrc/src/main/kotlin/uk/gov/justice/digital/hmpps/plugins/JibConfigPlugin.kt
- projects/person-search-index-from-delius/container/Dockerfile
- tools/build.gradle.kts
- tools/eclipse-temurin/17-jre/Dockerfile
- tools/eclipse-temurin/17-jre/build.gradle.kts
- tools/opensearch-logstash/8/Dockerfile
- tools/opensearch-logstash/8/build.gradle.kts
- tools/settings.gradle.kts
This allows us to upgrade dependencies in our base images without waiting for upstream changes. It also gives us a place to add any common images for dev tooling etc, that don't correspond to deployable services.
Happy to discuss whether or not this is a useful idea.  I'm not tied to it so would be keen to get other people's thoughts.
Note: the branch build failure is expected, as the base image hasn't been pushed to ghcr.io yet.  It'll be pushed when this branch is merged to main.
> PI-442 Added a set of shared tools and base images

- .github/dependabot.yml
- .github/workflows/tools.yml
- tools/eclipse-temurin/19-jre-jammy/Dockerfile
- tools/eclipse-temurin/19-jre-jammy/build.gradle.kts
- tools/settings.gradle.kts
After trying in https://github.com/ministryofjustice/community-api/pull/732 to switch to a multiplatform build, it became apparent that there are no arm64 17 jre alpine Docker images, and also the underlying image in this repo is not multiplatform. This adds a new multiplatform image based on the version 18 Eclipse Temurin image, which is multiplatform, and used in production via the Kotlin template.
> Add multiplatform OpenJDK image

- tools/eclipse-temurin/19-jre-jammy/build.gradle.kts
This ensures we only push the images we’ve built, as loading to local registry does not work with multi-platform builds.
> Add `push` arg for Dockerx multi-platform images

- projects/risk-assessment-scores-to-delius/src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/IntegrationTest.kt
- projects/risk-assessment-scores-to-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/listener/MessageListener.kt
- projects/risk-assessment-scores-to-delius/src/test/kotlin/uk/gov/justice/hmpps/listener/MessageListenerTest.kt
Both RSR and OGRS messages will use "risk-assessment.scores.determined" as the eventType in the attributes, and will use the eventType in the message body to specify which scores (RSR or OGRS) were sent.
> PI-492 Update risk assessment scores consumer to use eventType from message body

- projects/approved-premises-and-delius/.trivyignore
- projects/approved-premises-and-oasys/.trivyignore
- projects/pre-sentence-reports-to-delius/.trivyignore
- projects/prison-case-notes-to-probation/.trivyignore
- projects/prison-custody-status-to-delius/.trivyignore
- projects/risk-assessment-scores-to-delius/.trivyignore
- projects/tier-to-delius/.trivyignore
- projects/workforce-allocations-to-delius/.trivyignore
* Removes commons-text:1.9 suppression following app insights upgrade
* Adds expiry date for existing suppressions
* Adds suppressions for approved-premises projects
> PI-511 Update Trivy suppressions

- .github/actions/build-and-test/action.yml
- .github/actions/check-changes/parse-changes.sh
- .github/actions/delius-deploy/action.yml
- .github/workflows/bootstrap.yml
- .github/workflows/deploy.yml
* Replaces "::set-output" with $GITHUB_OUTPUT file - see https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
* Updates configure-aws-credentials action to use Node v16 - see https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/
> PI-482 Remove usage of deprecated CI features

- .github/workflows/security.yml
- build.gradle.kts
[View the report](https://analysiscenter.veracode.com/auth/index.jsp#ViewReportsDetailedReport:77328:1567873:21728097:21699554:21715204:::::4959212)
We're currently scoring 99/100 on this project, with the only "flaw" due to disabling CSRF.  I've proposed a mitigation, but I'm not sure how they get approved in the Veracode app. 
Note: I've re-enabled the Gradle jar creation as part of this PR.  It doesn't seem to add much time (if any) to the build, so I don't think this is a problem. 
<details>
<summary>The alternative was to extract the jars and class files from the Jib images like below, but that felt a bit messy.</summary>
```shell
for project in $(echo '${{ needs.get-projects.outputs.projects }}' | jq -r '.[]'); do
mkdir -p package/{}
docker pull ${DOCKER_PREFIX}/{}:latest …
```
> PI-489 Implement Veracode static code scanning

- .github/dependabot.yml
This is no longer needed (and results in duplicate PRs), following this issue being closed: https://github.com/dependabot/dependabot-core/issues/2180
> Remove explicit /buildSrc dependabot location

- projects/risk-assessment-scores-to-delius/deploy/values-dev.yml
- projects/risk-assessment-scores-to-delius/deploy/values-preprod.yml
- projects/risk-assessment-scores-to-delius/deploy/values-prod.yml
- projects/risk-assessment-scores-to-delius/deploy/values.yml
- projects/tier-to-delius/deploy/values-dev.yml
- projects/tier-to-delius/deploy/values-preprod.yml
- projects/tier-to-delius/deploy/values-prod.yml
- projects/tier-to-delius/deploy/values.yml
When the new queues are created in cloud-platform-environments, the GitHub secrets will be overwritten by the new queue details.  This change ensures we continue consuming from the old queues until we're ready to switch over.
> PI-86 Prepare for SQS namespace migration

- projects/prison-custody-status-to-delius/deploy/values-prod.yml
Note: This prevents us from deploying fixes for a while, so hopefully we can get testing completed soon.  In future, it may be better to hold off on merging things like this until they're ready for prod.
> Disable temporary licence recall processing in production.

- .github/workflows/end-to-end-tests.yml
Adds an option to specify the test branch when manually running e2e tests.
Testing here: https://github.com/ministryofjustice/hmpps-probation-integration-services/actions/runs/3639675571/jobs/6143358704
> Run end-to-end tests from a branch

- projects/risk-assessment-scores-to-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/integrations/delius/RiskScoreService.kt
Switches from a reluctant qualifier (`.+?`) to a character class exclusion (`[^]]++`) to prevent potentially inefficient backtracking.
Fixes Sonar issue: https://sonarcloud.io/project/issues?issues=AYUV9eDqLOACD6LyoOAG&open=AYUV9eDqLOACD6LyoOAG&id=ministryofjustice_hmpps-probation-integration-services
> PI-648 Improve regular expression and add event number message

- .github/actions/check-changes/action.yml
- .github/actions/check-changes/parse-changes.sh
- .github/workflows/pipeline.yml
* Adds additional directories into the "commons" filter
* Skips deployments when no changes detected (this should stop the pipeline from being marked as failed)
> PI-665 Improve pipeline change detection

- build.gradle.kts
This does give us better information in Sentry and in the Spring Boot /info endpoint - however I believe it's causing cache misses in CI builds.
First build: (11m 35s): https://github.com/ministryofjustice/hmpps-probation-integration-services/actions/runs/3740718788/jobs/6349417022
Second build (**3m 5s**): https://github.com/ministryofjustice/hmpps-probation-integration-services/actions/runs/3740832177/jobs/6349667068
> PI-639 Remove gradle-git-properties plugin

- .github/actions/check-changes/action.yml
- .github/actions/delius-deploy/action.yml
- .github/workflows/access.yml
* The new workflow runs whenever the access.yml file changes, instead of on deployment
* Audit user creation is disabled in preprod, this will be populated by a DB trigger when prod is updated
Related PR: https://github.com/ministryofjustice/hmpps-delius-pipelines/pull/558
Test run: https://github.com/ministryofjustice/hmpps-probation-integration-services/actions/runs/3741802757
> PI-636 Move DB user creation to a separate workflow

- .github/workflows/security.yml
Quotes aren't required when running locally with zsh, but cause the comparison on line 83 to fail when not provided in bash.
> PI-683 Fix Trivy workflow from closing/re-opening issues

- .github/workflows/docs.yml
Removes the dependency on the dev environment, and means we can use GitHub-hosted runners instead of our own.
> PI-811 Build OpenAPI spec during tech-docs build

- projects/refer-and-monitor-and-delius/deploy/database/access.yml
Otherwise sqlplus prompts for a value, causing the SSM job to hang:
```shell
oracle@delius-db-1:delius-test:~ $ sh -c '. ~/.bash_profile && sqlplus -s / as sysdba @create-user.sql'
Enter value for monitor: ^C
oracle@delius-db-1:delius-test:~ $ sh -c '. ~/.bash_profile && sqlplus -s / as sysdba @create-user.sql'
success
```
> PI-801 Remove '&' character from forename

- .github/workflows/label-pull-requests.yml
Also prevents script injection from rogue PRs - see https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#example-of-a-script-injection-attack
> PI-819 Fix for unexpected characters in PR title

- projects/person-search-index-from-delius/container/pipelines/contact/statement.sql
- projects/person-search-index-from-delius/container/pipelines/person/statement.sql
- projects/person-search-index-from-delius/container/scripts/monitor-reindexing.sh
- projects/person-search-index-from-delius/container/scripts/startup.sh
- projects/person-search-index-from-delius/deploy/values.yaml
This change ensures the monitor-reindexing.sh script only switches indexes after 'indexReady' is set to true in the metadata document (id=-1), which will only happen when :sql_last_value is higher than the maximum id of the table (i.e. when Logstash has processed every row).
> PI-879 Only switch indexes after all rows have been loaded

- projects/person-search-index-from-delius/container/pipelines/person/logstash-full-load.conf
Due to the sparseness of the OFFENDER table, a batch size of 100mil will result in 15 batches of ~150k records.  Whereas before with a batch_size of 1mil, we would get around 45 batches of ~50k records.  The higher batch size should result in a more consistent throughput, as Logstash will have more records to process while each DB query is running. 
| "COUNT(OFFENDER_ID)" | "FLOOR(OFFENDER_ID/100000000)" |
|----------------------|--------------------------------|
| 64964                | 0                              |
| 94544                | 1                              |
| 18206                | 2                              |
| 134219               | 3                              |
| 127759               | 4                              |
| 295008               | 5 …
> PI-830 Increase batch size for person-full-load pipeline

- .github/workflows/bootstrap.yml
- projects/person-search-index-from-delius/container/scripts/startup.sh
- projects/person-search-index-from-delius/deploy/templates/contact-reindex-cronjob.yml
- projects/person-search-index-from-delius/deploy/templates/person-reindex-cronjob.yml
Also doubled the contact reindexing batch size, to make better use of the available memory.
View the status of our cron jobs here: https://ministryofjustice.sentry.io/crons/
> PI-919 Add Sentry cron monitoring

- .github/actions/render-project-template/action.yml
- .github/workflows/cleanup.yml
- .github/workflows/docs.yml
To publish draft tech docs from a branch, run the [Documentation workflow](https://github.com/ministryofjustice/hmpps-probation-integration-services/actions/workflows/docs.yml) with the "Deploy" option enabled.
The URL will start with `https://ministryofjustice.github.io/hmpps-probation-integration-services/**tech-docs-drafts**/`.
For example,
https://ministryofjustice.github.io/hmpps-probation-integration-services/tech-docs-drafts/make-recall-decisions-and-delius
> PI-923 Add support for publishing draft tech docs

- .github/workflows/deploy.yml
Reduces timeouts/failures by ensuring deployments don't run in parallel for the same project + environment.
> Set concurrency group for deploy workflow

- projects/make-recall-decisions-and-delius/src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/UserAccessIntegrationTest.kt
- projects/make-recall-decisions-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/api/controller/UserController.kt
- projects/make-recall-decisions-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/integrations/delius/user/access/UserAccessRepository.kt
- projects/make-recall-decisions-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/integrations/delius/user/staff/UserStaffRepository.kt
- projects/workforce-allocations-to-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/integrations/delius/user/access/UserAccessRepository.kt
Also makes username case-insensitive. Note: `upper` is used instead of `lower` because there is an index on `upper(distinguished_name)`.
> PI-577 Return 404 for user access when case not found

- .github/workflows/cleanup.yml
It takes a while to install git-filter-repo via homebrew, as it installs a bunch of dependencies including another copy of python. This should speed things up and minimise the amount of time between pulling and pushing, which will hopefully reduce the amount of ref lock errors we've seen.
> PI-994 Attempt to fix cleanup job failures

- projects/unpaid-work-and-delius/deploy/values-prod.yml
This reverts commit 20d45caa91c0a5fc327405035758331ed977ecd1.
We have confirmed that requests are fully-formed when they get to Alfresco.
> PI-111 Revert "PI-1112 Log requests to Alfresco (#1566)"

- projects/refer-and-monitor-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/integrations/delius/contact/ContactRepository.kt
- projects/refer-and-monitor-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/service/AppointmentService.kt
The `contact.external_reference` index hasn't been applied to the database yet (see [DST-10414](https://jira.engineering-dev.probation.hmpps.dsd.io/browse/DST-10414)), so we need to additionally filter by CRN to get reasonable performance. This means we won't be able to categorise merged cases for now.
> PI-1093 Add CRN to AppointmentNotFound query

- projects/person-search-index-from-delius/container/pipelines/contact/logstash-full-load.conf
- projects/person-search-index-from-delius/container/pipelines/person/logstash-full-load.conf
- projects/person-search-index-from-delius/container/scripts/monitor-reindexing.sh
- projects/person-search-index-from-delius/deploy/templates/contact-reindex-cronjob.yml
- projects/person-search-index-from-delius/deploy/templates/person-reindex-cronjob.yml
This ensures that ImagePullBackOff errors don't block subsequent image builds from running.
Also removes SQL logging, as it's just noise.
> PI-983 Replace jobs that have failed to start

- .github/actions/docker-build/action.yml
Workaround for corrupted images due to https://github.com/snok/container-retention-policy/issues/63
> PI-983 Disable provenance for Docker builds

- projects/person-search-index-from-delius/container/pipelines/person/statement.sql
Fixes error:
```
[logstash.inputs.jdbc     ][person-full-load][load-all-records] Exception when executing JDBC query {
:exception=>Sequel::DatabaseError, 
:message=>"Java::JavaSql::SQLException: ORA-40478: output value too large (maximum: 4000)\n", 
:cause=>"#<Java::JavaSql::SQLException: ORA-40478: output value too large (maximum: 4000)\n>"
}
```
> PI-1173 Handle disability notes CLOB

- .github/workflows/analyse.yml
- .github/workflows/build.yml
so it happens in parallel to the build/deployment
Unfortunately I can't test this from the branch because `workflow_run` only works after merge: https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_run
> Note: This event will only trigger a workflow run if the workflow file is on the default branch.
> PI-1174 Remove Sonar analysis from the pipeline

- .github/dependabot.yml
- projects/person-search-index-from-delius/.trivyignore
- projects/person-search-index-from-delius/container/Dockerfile
Also upgrade Logstash and include it in Dependabot config.
> PI-1185 Suppress CVE-2023-34455 in Logstash image

- projects/person-search-index-from-delius/container/scripts/startup.sh
This configures the cluster settings any time a container starts, to ensure the settings are always up to date.
> PI-1191 Disable index auto-creation

- .github/dependabot.yml
AWS typically releases one or more new versions per day, hopefully this change stops us being bombarded with Dependabot updates.
> PI-1178 Reduce frequency of AWS SDK updates

- .github/dependabot.yml
Turns out having separate schedules for the same package manager isn't supported. See https://github.com/dependabot/dependabot-core/issues/1778.
> PI-1178 Ignore patch versions instead of having separate schedules

- .github/workflows/access.yml
Usernames are being created with extra "/" characters e.g. "project_/name" instead of "project_name".
Bug introduced in this commit: https://github.com/ministryofjustice/hmpps-probation-integration-services/commit/26f47829e1063e95160573cad2d881b994d2127a#diff-2b6be7268c958935f3ed5a7f4840ded6664b7d59bef9f46c09bb8223370537e2R124
> Fix DB username formatting

- .github/workflows/bootstrap.yml
The SQS policy had to be separated into a `queue` and `dlq` policy, because the original policy exceeded the PolicySize quota (see https://github.com/ministryofjustice/cloud-platform-environments/pull/14540/files).  This PR ensures the bootstrap works with the new format.
> PI-1226 Update bootstrapping to handle new queue policy format

- projects/manage-pom-cases-and-delius/src/dev/kotlin/uk/gov/justice/digital/hmpps/data/DataLoader.kt
- projects/manage-pom-cases-and-delius/src/dev/kotlin/uk/gov/justice/digital/hmpps/data/generator/ProviderGenerator.kt
- projects/manage-pom-cases-and-delius/src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/ApiIntegrationTest.kt
- projects/manage-pom-cases-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/integrations/delius/person/entity/Person.kt
- projects/manage-pom-cases-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/integrations/delius/provider/entity/Team.kt
- projects/manage-pom-cases-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/services/mapping/ProbationRecordMapping.kt
- projects/manage-pom-cases-and-delius/src/test/kotlin/uk/gov/justice/digital/hmpps/services/mapping/ProbationRecordMappingKtTest.kt
`local_delivery_unit_id` corresponds to Team Type, which isn't really used. `district_id` corresponds to what Delius now calls "Local Admin Unit", but what Community API called `localDeliveryUnit`.  MPC still expect the field to be called `localDeliveryUnit` in the response, even though what they really want is Local Admin Unit.  Hooray for Community API naming inconsistencies.
> PI-1378 Update to use district table for LAU

- projects/approved-premises-and-delius/.trivyignore
- projects/approved-premises-and-oasys/.trivyignore
- projects/court-case-and-delius/.trivyignore
- projects/create-and-vary-a-licence-and-delius/.trivyignore
- projects/custody-key-dates-and-delius/.trivyignore
- projects/domain-events-and-delius/.trivyignore
- projects/effective-proposal-framework-and-delius/.trivyignore
- projects/external-api-and-delius/.trivyignore
- projects/hmpps-auth-and-delius/.trivyignore
- projects/make-recall-decisions-and-delius/.trivyignore
- projects/manage-offences-and-delius/.trivyignore
- projects/manage-pom-cases-and-delius/.trivyignore
- projects/offender-events-and-delius/.trivyignore
- projects/opd-and-delius/.trivyignore
- projects/pathfinder-and-delius/.trivyignore
- projects/pre-sentence-reports-to-delius/.trivyignore
- projects/prison-case-notes-to-probation/.trivyignore
- projects/prison-custody-status-to-delius/.trivyignore
- projects/prison-education-and-delius/.trivyignore
- projects/refer-and-monitor-and-delius/.trivyignore
- projects/resettlement-passport-and-delius/.trivyignore
- projects/risk-assessment-scores-to-delius/.trivyignore
- projects/sentence-plan-and-delius/.trivyignore
- projects/sentence-plan-and-oasys/.trivyignore
- projects/soc-and-delius/.trivyignore
- projects/tier-to-delius/.trivyignore
- projects/unpaid-work-and-delius/.trivyignore
- projects/workforce-allocations-to-delius/.trivyignore
The snakeyaml upgrade is still coming in Spring Boot 3.2, which is in preview and due for release in November.
> PI-1485 Extend suppression for CVE-2022-1471

- projects/hmpps-auth-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/controller/UserController.kt
I've kept this consistent with the existing role name for now, we can change these together to match the new naming format when we change the rest over.
> PI-1493 Add new role for user details endpoint 

- projects/pre-sentence-reports-to-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/integrations/delius/document/DocumentService.kt
Previously, an empty PDF would be uploaded to the Alfresco when the initial draft was started.  Following the recent changes, Delius now uploads a .doc file instead as the draft.  However, the filename remains the same after the report is completed.
So we end up with a PDF document saved as e.g.
```
Nat Short format pre-sentence report_13102023_112036_Larson_D_X729742.doc
```
This PR updates the extension to .pdf before saving
> PI-1558 Update PSR extension to PDF when complete

- .github/workflows/readonly.yml
This prevents endless polling of the standby database, as we cannot delete from the offender_delta or domain_event tables
> PI-1539 Disable event publishers in read-only mode

- projects/prison-custody-status-to-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/integrations/delius/person/manager/prison/PrisonManagerService.kt
- projects/prison-custody-status-to-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/integrations/delius/person/manager/prison/entity/PrisonManager.kt
- projects/prison-custody-status-to-delius/src/test/kotlin/uk/gov/justice/digital/hmpps/integrations/delius/person/manager/prison/PrisonManagerServiceTest.kt
We may also need to apply a similar change to Workforce COM allocations, although we seemingly haven't hit this issue there yet.  I'll try this out in the Custody Status integration for a while first, then if we want to apply it elsewhere we can put another ticket in.
Also I don't think MPC handles historical allocations at all, we might need to look at that.
> PI-1607 Handle missing history for historical POM allocations

- libs/audit/src/main/kotlin/uk/gov/justice/digital/hmpps/audit/service/OptimisationTables.kt
- libs/audit/src/main/kotlin/uk/gov/justice/digital/hmpps/datasource/DeliusConnectionProvider.kt
- libs/audit/src/main/kotlin/uk/gov/justice/digital/hmpps/datasource/OptimisationContext.kt
- libs/audit/src/test/kotlin/uk/gov/justice/digital/hmpps/audit/service/OptimisationTablesTest.kt
- libs/audit/src/test/kotlin/uk/gov/justice/digital/hmpps/datasource/DeliusConnectionProviderTest.kt
- projects/tier-to-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/integrations/tier/TierService.kt
- projects/tier-to-delius/src/test/kotlin/uk/gov/justice/digital/hmpps/integrations/tier/TierServiceTest.kt
- projects/workforce-allocations-to-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/service/AllocateEventService.kt
- projects/workforce-allocations-to-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/service/AllocatePersonService.kt
- projects/workforce-allocations-to-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/service/AllocateRequirementService.kt
- projects/workforce-allocations-to-delius/src/test/kotlin/uk/gov/justice/digital/hmpps/service/AllocateEventServiceTest.kt
- projects/workforce-allocations-to-delius/src/test/kotlin/uk/gov/justice/digital/hmpps/service/AllocatePersonServiceTest.kt
- projects/workforce-allocations-to-delius/src/test/kotlin/uk/gov/justice/digital/hmpps/service/AllocateRequirementServiceTest.kt
(no call to stored procedure) 
https://portal.azure.com/#blade/AppInsightsExtension/DetailsV2Blade/DataModel/%7B%22eventId%22:%22b16a403f-604d-43b1-a2c6-57f57f549b20%22,%22timestamp%22:%222023-11-02T10:31:59.017Z%22%7D/ComponentId/%7B%22Name%22:%22nomisapi-t3%22,%22ResourceGroup%22:%22nomisapi-t3-rg%22,%22SubscriptionId%22:%22c27cfedb-f5e9-45e6-9642-0fad1a5c94e7%22%7D
(calls stored procedure)
https://portal.azure.com/#blade/AppInsightsExtension/DetailsV2Blade/DataModel/%7B%22eventId%22:%22c24d12e5-5191-4713-969c-a74bc9f922f0%22,%22timestamp%22:%222023-11-02T13:36:31.678Z%22%7D/ComponentId/%7B%22Name%22:%22nomisapi-t3%22,%22ResourceGroup%22:%22nomisapi-t3-rg%22,%22SubscriptionId%22:%22c27cfedb-f5e9-45e6-9642-0fad1a5c94e7%22%7D
> PI-1615 Move caseload rebuild into afterCommit hook

- projects/approved-premises-and-delius/src/dev/kotlin/uk/gov/justice/digital/hmpps/data/DataLoader.kt
- projects/approved-premises-and-delius/src/dev/kotlin/uk/gov/justice/digital/hmpps/data/ProbationCaseDataLoader.kt
- projects/approved-premises-and-delius/src/dev/kotlin/uk/gov/justice/digital/hmpps/data/generator/ProbationCaseGenerator.kt
- projects/approved-premises-and-delius/src/dev/kotlin/uk/gov/justice/digital/hmpps/data/generator/StaffGenerator.kt
This adds some additional seed data to `approved-premises-and-delius` to allow us to run the service locally with some of our existing seed data on the other services.
> Add some additional seed data for CAS

- projects/dps-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/config/security/StreamingHeadersSecurityConfigurer.kt
- projects/dps-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/service/DocumentService.kt
Fixes intermittent errors:
```
NullPointerException
Cannot invoke "org.apache.tomcat.util.http.MimeHeaderField.getName()" because "this.headers[i]" is null
```
> PI-1684 Workaround for thread-safety bug in Spring streaming response

- .github/workflows/docs.yml
Fixes tech-docs deployment: https://github.com/ministryofjustice/hmpps-probation-integration-services/actions/runs/7354088094/job/20020884326
> Revert upgrade to actions/download-artifact@v4

- projects/create-and-vary-a-licence-and-delius/src/dev/kotlin/uk/gov/justice/digital/hmpps/data/DataLoader.kt
- projects/create-and-vary-a-licence-and-delius/src/dev/kotlin/uk/gov/justice/digital/hmpps/data/generator/CaseloadGenerator.kt
- projects/create-and-vary-a-licence-and-delius/src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/CaseloadIntegrationTest.kt
- projects/create-and-vary-a-licence-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/api/resource/TeamResource.kt
- projects/create-and-vary-a-licence-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/integrations/delius/caseload/entity/Caseload.kt
- projects/create-and-vary-a-licence-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/service/TeamService.kt
- projects/create-and-vary-a-licence-and-delius/src/test/kotlin/uk/gov/justice/digital/hmpps/api/resource/TeamResourceTest.kt
- projects/create-and-vary-a-licence-and-delius/src/test/kotlin/uk/gov/justice/digital/hmpps/service/TeamServiceTest.kt
N.B - Although pagination has been attempted in the community API, this is not complete as the response object is not wrapped in a pagination object. Also, defaults are currently being used by the client. Effectively the client is not using pagination. Therefore have decided to leave pagination off this endpoint at the moment
> PI-1534: Added CVL Caseload by Team Code

- projects/hmpps-auth-and-delius/src/dev/kotlin/uk/gov/justice/digital/hmpps/data/DataLoader.kt
- projects/hmpps-auth-and-delius/src/dev/kotlin/uk/gov/justice/digital/hmpps/data/generator/UserGenerator.kt
- projects/hmpps-auth-and-delius/src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/UserDetailsIntegrationTest.kt
- projects/hmpps-auth-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/controller/UserController.kt
- projects/hmpps-auth-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/entity/User.kt
- projects/hmpps-auth-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/service/UserService.kt
Ive had to add a /user/details/{userId} endpoint as user/{username} already in use. Also can't easily add query param as /user/?email already in use which (apart from being messy to introduce a userId query param) currently returns a list. We want a 404 or single user object
> PI-1785: Added get user details by id

- projects/cas2-and-delius/deploy/database/access.yml
(max length of column is 35 characters)
"Short-Term Accommodation" is the name used within the service: https://github.com/ministryofjustice/hmpps-approved-premises-api/blob/1e45b3cc69bcd1ebe21a26999f1e4cbdf9b699e1/src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/model/reference/Cas2ApplicationStatusSeeding.kt#L31
> PI-1777 Reduce length of forename

- projects/make-recall-decisions-and-delius/src/dev/kotlin/uk/gov/justice/digital/hmpps/data/generator/EventGenerator.kt
- projects/make-recall-decisions-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/integrations/delius/casesummary/Release.kt
- projects/make-recall-decisions-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/service/CaseSummaryService.kt
- projects/make-recall-decisions-and-delius/src/test/kotlin/uk/gov/justice/digital/hmpps/service/CaseSummaryServiceTest.kt
The overview endpoint previously returned null if there were multiple active events.  This change looks at all active custodial events and returns the most recent release/recall dates.
> PI-1826 Return most recent release date

- .github/actions/analyse/action.yml
- .github/actions/render-project-template/action.yml
- .github/workflows/build.yml
- .github/workflows/docs.yml
Uses the new `merge-multiple` option in download-artifact to get the same behaviour as before.  See https://github.com/actions/upload-artifact/blob/main/docs/MIGRATION.md#multiple-uploads-to-the-same-named-artifact
> PI-1851 Upgrade actions/upload-artifact and actions/download-artifact to v4

- .github/actions/analyse/action.yml
When we have multiple test results for the same project (e.g. for the libs), it previously attempted to merge the XML files which resulted in parse errors later on. This ensures files are overwritten instead of merged.
> PI-1851 Fix test result XML files being merged

- .github/workflows/access.yml
This allows us to continue creating the client_id trigger.
See https://github.com/ministryofjustice/hmpps-delius-pipelines/pull/793
> PI-1929 Explicitly disable audit user creation in preprod

- projects/tier-to-delius/deploy/values-dev.yml
Error displayed against the replicaset:
```
Warning  FailedCreate  14m replicaset-controller  Error creating: Pod "tier-to-delius-5bdb457bfb-xspkt" is invalid: spec.containers[0].resources.requests: Invalid value: "4": must be less than or equal to cpu limit of 1
```
Weirdly the deployment failed silently - might need to look into that: https://github.com/ministryofjustice/hmpps-probation-integration-services/actions/runs/8465613802/job/23335290107
> PI-2019 Fix typo in increasing tier-to-delius resources

- projects/prison-identifier-and-delius/deploy/values-dev.yml
- projects/prison-identifier-and-delius/src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/MergeIntegrationTest.kt
- projects/prison-identifier-and-delius/src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/ProbationMatchingIntegrationTest.kt
- projects/prison-identifier-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/messaging/Handler.kt
Disables the dry-run flag for event-driven matching in dev, preprod and prod.
Note: dry-run is still enabled for bulk matching.
> PI-2051 Enable prison-identifier-and-delius matching in prod

- projects/workforce-allocations-to-delius/deploy/templates/initial-allocations-report.yaml
Slack rejects it as the file is too large to fit into a snippet
> PI-2241 Remove snippet_type argument

- libs/commons/src/main/kotlin/uk/gov/justice/digital/hmpps/ldap/LdapTemplateExtensions.kt
- libs/commons/src/test/kotlin/uk/gov/justice/digital/hmpps/ldap/LdapTemplateExtensionsTest.kt
Fixes roles being created in the LDAP without the full aliasedObjectName.
* `roleContext.dn`: cn=ROLE1,cn=ndRoleCatalogue
* `roleContext.nameInNamespace`: cn=ROLE1,cn=ndRoleCatalogue,ou=Users,dc=moj,dc=com
> PI-2255 Ensure full DN is used for aliasedObjectName attribute

- projects/refer-and-monitor-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/messaging/ReferralEndSubmitted.kt
- projects/refer-and-monitor-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/service/NsiService.kt
R&M aren't sending it yet in production.  Note: they will send an empty string once they deploy their changes, hence the `takeIf { it.isNotEmpty() }`.
> PI-2231 Handle null withdrawalCode

- projects/approved-premises-and-delius/src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/StaffControllerIntegrationTest.kt
- projects/approved-premises-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/service/StaffService.kt
- projects/core-person-record-and-delius/src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/CorePersonIntegrationTest.kt
- projects/core-person-record-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/api/resource/PersonResource.kt
* Approved Premises API does not currently map the page fields, so this won't break anything there: https://github.com/ministryofjustice/hmpps-approved-premises-api/blob/cef16013ba101d8286e0161e85649a1626a29c9b/src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/model/deliuscontext/StaffMembersPage.kt#L3-L5
* Core Person Record only calls the paged endpoint on an ad-hoc basis to do a full load, so we can just co-ordinate the rollout with them. See https://github.com/ministryofjustice/hmpps-person-record/pull/426
> PI-2291 Switch to Spring's PagedModel for responses

- projects/approved-premises-and-delius/src/dev/kotlin/uk/gov/justice/digital/hmpps/data/DataLoader.kt
- projects/approved-premises-and-delius/src/dev/kotlin/uk/gov/justice/digital/hmpps/data/generator/AddressGenerator.kt
- projects/approved-premises-and-delius/src/dev/kotlin/uk/gov/justice/digital/hmpps/data/generator/ApprovedPremisesGenerator.kt
- projects/approved-premises-and-delius/src/dev/kotlin/uk/gov/justice/digital/hmpps/data/generator/ReferenceDataGenerator.kt
- projects/approved-premises-and-delius/src/dev/kotlin/uk/gov/justice/digital/hmpps/data/generator/TeamGenerator.kt
To get the Approved Premises E2E tests running properly in the local development environment as well as in the deployed dev/test env we need to look up staff for the "AP Test 10" Premises (QCode 710) in AP-and-Delius, in both the local and the deployed dev/test environments.
In this commit we create a new AP in the local ('dev' namespace) AP-and-Delius context with the expected QCode to match what's already in use in the dev/test environment.
This will allow our locally running API to ask for staff members:
`GET https://ap-and-delius/approved-premises/Q710/staff`
and execute the sanme E2E test in both local and deployed environments.
> Seed Approved Premises for local testing

- projects/approved-premises-and-delius/src/dev/kotlin/uk/gov/justice/digital/hmpps/data/ProbationCaseDataLoader.kt
- projects/approved-premises-and-delius/src/dev/kotlin/uk/gov/justice/digital/hmpps/data/generator/ProbationCaseGenerator.kt
The Approved Premises local E2E tests have need of a "probation case" (person leaving custody) to use in E2E tests which rely on a manual or "ad hoc" booking. These bookings can only be made for people who don't have any existing applications with the service. This is most reliably achieved by using a distinct probation case.
In this commit we seed a case with CRN X320811, which [ties in with seeding at CommunityAPI][] -- which is still being used at present for fetching a list of convictions:
```
http://community-api/secure/offenders/crn/X320811/convictions
```
[ties in with seeding at CommunityAPI]:
https://github.com/ministryofjustice/community-api/blob/736ac63ff7705a0c8d998ed2773d59563b0fdea4/src/main/resources/db/data/V1_9__offender_X320811_custody_status_data.sql#L1
> Seed probation case for Approved Premises E2E testing

- projects/approved-premises-and-delius/src/dev/kotlin/uk/gov/justice/digital/hmpps/data/DataLoader.kt
- projects/approved-premises-and-delius/src/dev/kotlin/uk/gov/justice/digital/hmpps/data/ProbationCaseDataLoader.kt
- projects/approved-premises-and-delius/src/dev/kotlin/uk/gov/justice/digital/hmpps/data/generator/LimitedAccessGenerator.kt
- projects/approved-premises-and-delius/src/dev/kotlin/uk/gov/justice/digital/hmpps/data/generator/ProbationCaseGenerator.kt
- projects/approved-premises-and-delius/src/dev/kotlin/uk/gov/justice/digital/hmpps/data/generator/StaffGenerator.kt
This commit enhances the approved-premises-and-delius seed data to include two new offenders and two new users to supports testing of LAO access in Approved Premises.
Two new users and cases are added:
* LAOFULLACCESS - has access to the new excluded case X400000
* LAORESTRICTED - does not have access to the new restricted case X400001
> Seed LAO Test Data for Approved Premises

- libs/messaging/src/main/kotlin/uk/gov/justice/digital/hmpps/documentation/AsyncApiReferencingSerializer.kt
- projects/approved-premises-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/messaging/Handler.kt
- projects/assessment-summary-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/messaging/Handler.kt
- projects/cas2-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/messaging/Handler.kt
- projects/cas3-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/messaging/Handler.kt
- projects/court-case-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/messaging/Handler.kt
- projects/custody-key-dates-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/messaging/Handler.kt
- projects/custody-key-dates-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/messaging/Notifier.kt
- projects/make-recall-decisions-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/messaging/Handler.kt
- projects/manage-pom-cases-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/messaging/Notifier.kt
- projects/manage-pom-cases-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/messaging/PomCaseMessageHandler.kt
- projects/opd-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/messaging/Handler.kt
- projects/prison-custody-status-to-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/messaging/Handler.kt
- projects/prison-identifier-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/messaging/Handler.kt
- projects/prison-identifier-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/messaging/Notifier.kt
- templates/projects/message-listener-with-api-client/src/main/kotlin/uk/gov/justice/digital/hmpps/messaging/Handler.kt
- templates/projects/message-listener/src/main/kotlin/uk/gov/justice/digital/hmpps/messaging/Handler.kt
Using `messageId` caused a conflict if the same `messageId` was referenced multiple times. This switches to use `title` instead, which results in the same output.
> Fix AsyncAPI docs with duplicate `messageId`s

- projects/workforce-allocations-to-delius/deploy/templates/initial-allocations-report.yaml
- projects/workforce-allocations-to-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/integrations/delius/allocations/InitialAllocation.kt
- projects/workforce-allocations-to-delius/src/main/resources/application.yml
The exception is a "Socket interrupted" error exactly 30 seconds after the request is started, while reading data from the database in the Oracle JDBC driver.  The error is logged but because the response headers have already been sent, the status is still 200 OK.  The interruption happens in Oracle's TimeoutSocketChannel class.  When this class opens a DB connection, or starts reading data, it schedules an interruption to occur after a given socket timeout (soTimeout).  This sent me down the rabbit hole that the JDBC driver must have been causing the error after 30 seconds, however the socket timeout defaults to 0 (meaning no timeout), so it wasn't that.
Turns out actually Spring was interrupting the thread after its async timeout, which defaults to 30 seconds.  I definitely did look …
> PI-2330 Fix truncated allocations report due to async timeout

- projects/manage-offences-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/messaging/Handler.kt
- projects/manage-offences-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/service/OffenceService.kt
- projects/manage-offences-and-delius/src/test/kotlin/uk/gov/justice/digital/hmpps/messaging/HandlerTest.kt
- projects/manage-offences-and-delius/src/test/kotlin/uk/gov/justice/digital/hmpps/service/OffenceServiceTest.kt
To prevent duplicate entries in the offence report for failures
> PI-2401 Move telemetry out of offence creation transaction

- projects/feature-flags/deploy/templates/grafana-dashboards.yml
The dashboard is shared across dev/preprod/prod, so only needs to be created once. Attempting to create it 3 times is currently causing errors in Grafana.
> Only create flipt dashboard in dev namespace

- .github/dependabot.yml
- .github/workflows/check.yml
- .github/workflows/dependabot.yml
- .github/workflows/docs.yml
Also reduced frequency, all Dependabot updates will now happen on Monday.
> PI-2410 Auto-merge minor+patch Dependabot PRs

- projects/assessment-summary-and-delius/src/dev/kotlin/uk/gov/justice/digital/hmpps/data/DataLoader.kt
- projects/assessment-summary-and-delius/src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/IntegrationTest.kt
- projects/assessment-summary-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/service/RiskService.kt
The main change is here: https://github.com/ministryofjustice/hmpps-probation-integration-services/pull/4150/files#diff-6d219cb7fa943dc8c6731b4504057c565de2e952813637d6fe1e16028c860fc6L23-R25
The rest was just a bit of tidy up to make it clearer (in my head at least) what was happening with the registrations.
> PI-2416 Don't change RoSH registrations when risk flags are null

- .github/workflows/reminders.yml
Currently it shows any pending prod deployments, but we could also use this to replace the existing DLQ notifications.
Example: https://mojdt.slack.com/archives/C033HPR0W91/p1726657493794909
> PI-2538 Add workflow for daily reminders

- .github/workflows/reminders.yml
Tested here: https://github.com/ministryofjustice/hmpps-probation-integration-services/actions/runs/11048772817
> PI-2551 Fix reminder appearing when there are no deployments

- projects/cas3-and-delius/src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/CASIntegrationTest.kt
- projects/cas3-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/config/RestClientConfig.kt
- projects/cas3-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/integrations/approvedpremises/Cas3ApiClient.kt
- projects/cas3-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/integrations/approvedpremises/EventDetails.kt
- projects/cas3-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/integrations/delius/AddressService.kt
- projects/cas3-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/integrations/delius/ContactService.kt
- projects/cas3-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/integrations/delius/ProviderService.kt
- projects/cas3-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/messaging/Handler.kt
- projects/cas3-and-delius/src/test/kotlin/uk/gov/justice/digital/hmpps/integrations/approvedpremises/AddressTest.kt
- projects/cas3-and-delius/src/test/kotlin/uk/gov/justice/digital/hmpps/integrations/approvedpremises/EventDetailsTest.kt
- projects/cas3-and-delius/src/test/kotlin/uk/gov/justice/digital/hmpps/integrations/delius/ProviderServiceTest.kt
If the start date is unexpectedly after the end date, then the case must have moved on and the current CAS3 address will be for a different booking.
Also fixed typo in package name.
> PI-2572 Only end CAS3 address if start date is before end date

- projects/person-search-index-from-delius/container/Dockerfile
- projects/person-search-index-from-delius/container/pipelines/contact/logstash-full-load.conf
- projects/person-search-index-from-delius/container/pipelines/contact/logstash-incremental.conf
This improves performance by allowing the DB to prepare and cache a single execution plan for the query.
> PI-2593 Switch to prepared statements for contact indexing

- projects/appointment-reminders-and-delius/src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/IntegrationTest.kt
- projects/appointment-reminders-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/model/UnpaidWorkAppointment.kt
- projects/appointment-reminders-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/repository/UpwAppointmentRepository.kt
The query now excludes cases that have an upcoming unpaid work appointment on one event, but another event showing as "in custody".  This can happen when someone is recalled or receives a new custodial sentence while completing unpaid work, and the future unpaid work appointments haven't yet been cleared down.
> PI-2543 Update UPW custody check

- projects/redrive-dead-letter-queues/deploy/values.yaml
This ensures all pods have a chance to start up
> PI-2617 Move DLQ redrive to 7am

- build.gradle.kts
Fixes errors being reported by IntelliJ when autowiring in tests and warnings on test names.
> Mark "integrationTest" and "dev" directories as test sources in IntelliJ

- .github/actions/get-build-info/action.yml
- .github/actions/setup-gradle/action.yml
Fixes cache invalidation errors: https://github.com/ministryofjustice/hmpps-probation-integration-services/actions/runs/11738620858/job/32701483985#step:5:20
```
Calculating task graph as configuration cache cannot be reused because the file system entry '.git/.probe-58218911-f51a-4ad7-bc53-06cd11b090a6' has been removed.
```
> PI-2624 Remove .git directory during Gradle build

- README.md
also moved code formatting to development section
> Added note about imports to code formatting section

- projects/approved-premises-and-delius/src/dev/kotlin/uk/gov/justice/digital/hmpps/data/generator/OffenceGenerator.kt
- projects/approved-premises-and-delius/src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/ProbationCaseIntegrationTest.kt
- projects/approved-premises-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/integrations/delius/person/offence/entity/Offence.kt
- projects/approved-premises-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/model/CaseDetail.kt
- projects/approved-premises-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/service/CaseService.kt
**Background**
- The `Community API`'s endpoint: `GET /secure/offenders/crn/{crn}/convictions` includes offence categories in the response
- We need these in the `Approved Premises` API to build offence descriptions
**PR Includes**
- For the `GET /probation-cases/{crn}/details` endpoint, retrieve the the extra offence categories from the DB and surface on the API response
> APS-1482 - Refactor GET case-detail endpoint to include offence categories

- projects/approved-premises-and-delius/src/dev/kotlin/uk/gov/justice/digital/hmpps/data/DataLoader.kt
- projects/approved-premises-and-delius/src/dev/kotlin/uk/gov/justice/digital/hmpps/data/generator/AddressGenerator.kt
- projects/approved-premises-and-delius/src/dev/kotlin/uk/gov/justice/digital/hmpps/data/generator/ApprovedPremisesGenerator.kt
- projects/approved-premises-and-delius/src/dev/kotlin/uk/gov/justice/digital/hmpps/data/generator/ReferenceDataGenerator.kt
- projects/approved-premises-and-delius/src/dev/kotlin/uk/gov/justice/digital/hmpps/data/generator/TeamGenerator.kt
- projects/approved-premises-and-delius/src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/StaffControllerIntegrationTest.kt
This commit adds new APs, Teams & Key Workers to the approved-premises-and-delius test data, ensuring we have at least one Key Worker for each AP QCode we use when testing the Approved Premise Application.
> APS-1516 Update Test APs, Teams & Key Workers

- .github/actions/get-build-info/action.yml
- .github/actions/setup-gradle/action.yml
May result in slightly longer build times due to configuration cache misses, but it's not the end of the world
> PI-2672 Fix Sonar change detection by leaving git directory

- projects/manage-supervision-and-delius/src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/LaoCaseloadIntegrationTest.kt
- projects/manage-supervision-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/api/controller/UserAccessController.kt
Required to check access for recently viewed screen
> MAN-192: Add endpoint to check user access for list of crns

- projects/approved-premises-and-delius/src/dev/kotlin/uk/gov/justice/digital/hmpps/data/generator/EventDetailsGenerator.kt
- projects/approved-premises-and-delius/src/dev/kotlin/uk/gov/justice/digital/hmpps/data/generator/StaffMemberGenerator.kt
- projects/approved-premises-and-delius/src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/StaffControllerIntegrationTest.kt
- projects/approved-premises-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/integrations/approvedpremises/StaffMember.kt
- projects/approved-premises-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/model/StaffResponse.kt
- projects/approved-premises-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/service/StaffService.kt
This commit removes staffIdentifier from the ap-and-delius API and updates the domain events to no longer expect a value for this field (which wasn’t being used anyway)
> APS-1642 - Remove staffIdentifier from ap-and-delius API

- .github/actions/merge-changes/check-deployments.sh
These were triggering a false-positive when `enabled: false` was set on the cron jobs.
> PI-2713 Fix deployments for projects with disabled batch jobs

- projects/person-search-index-from-delius/container/pipelines/contact/index/index-template-semantic.yml
Lucene supports radial search (unlike the default hnsw) while maintaining support for the cosine similarity space.
See:
* https://opensearch.org/docs/latest/search-plugins/knn/radial-search-knn/
* https://opensearch.org/docs/latest/search-plugins/knn/knn-index#method-definitions
> PI-2526 Switch to the lucene knn engine

- projects/person-search-index-from-delius/container/pipelines/contact/index/ingest-pipeline.tpl.json
To fix:
```
OpenSearch exception [type=illegal_argument_exception, reason=field [notes] is null, cannot process it.]
```
> PI-2526 Ignore missing notes when stripping out punctuation

- projects/redrive-dead-letter-queues/deploy/values.yaml
Integration services are scheduled to start up at 6:30, but occasionally take longer than 30 minutes as the Delius database is still warming up.
> PI-2751 Move DLQ redrive schedule back 30 minutes

- projects/custody-key-dates-and-delius/src/dev/kotlin/uk/gov/justice/digital/hmpps/data/DataLoader.kt
- projects/custody-key-dates-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/integrations/delius/custody/date/CustodyDateUpdateService.kt
- projects/custody-key-dates-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/integrations/delius/custody/date/Sentence.kt
Previously, when we encountered a case that had two key dates of the same type (with different dates), we would try to update the first one we found.  However, there's a chance we update the date to be the same as the date on the other key date - resulting in a key constraint error.  With this change, if we come across a case with multiple key dates of the same type - we delete all but one, then update the remaining one.
Resolves https://ministryofjustice.sentry.io/issues/6279152215
> PI-2930 Remove duplicate key dates

- libs/commons/src/main/kotlin/uk/gov/justice/digital/hmpps/datetime/DeliusDateTimeFormatter.kt
- projects/approved-premises-and-delius/src/dev/kotlin/uk/gov/justice/digital/hmpps/data/generator/AddressGenerator.kt
- projects/approved-premises-and-delius/src/dev/kotlin/uk/gov/justice/digital/hmpps/data/generator/ReferralGenerator.kt
- projects/approved-premises-and-delius/src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/MessagingIntegrationTest.kt
- projects/approved-premises-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/integrations/delius/approvedpremises/referral/entity/Residence.kt
- projects/approved-premises-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/service/AddressService.kt
- projects/approved-premises-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/service/NsiService.kt
- projects/approved-premises-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/service/ReferralService.kt
- projects/approved-premises-and-delius/src/test/kotlin/uk/gov/justice/digital/hmpps/service/AddressServiceTest.kt
- projects/approved-premises-and-delius/src/test/kotlin/uk/gov/justice/digital/hmpps/service/ApprovedPremisesServiceTest.kt
* On arrival, set the expected departure date on the residence
* On arrival, update any existing residence record in-place to prevent duplicates
* On booking changed, set the expected departure date on the residence if there is one
* On departure, only add an end-date to the main address if it is an AP address, and it was added before the departure date
> PI-2946 Arrival/departure changes for CAS1 integration

- projects/approved-premises-and-delius/src/dev/kotlin/uk/gov/justice/digital/hmpps/data/ProbationCaseDataLoader.kt
- projects/approved-premises-and-delius/src/dev/kotlin/uk/gov/justice/digital/hmpps/data/generator/ProbationCaseGenerator.kt
feat: adds a user to match the NOMS/CRN of an excluded offender in dev env
> CBA-412/fix-seed-data-for-local-to-match-dev

- libs/messaging/src/main/kotlin/uk/gov/justice/digital/hmpps/listener/AwsNotificationListener.kt
These are thrown for REST client timeouts since Spring Boot 3.4
> PI-2959 Retry CancellationException

- .github/actions/analyse/action.yml
- .github/actions/cloud-platform-deploy/action.yml
- .github/actions/get-build-info/action.yml
- .github/actions/gradle-build/action.yml
- .github/actions/setup-gradle/action.yml
- .github/workflows/build.yml
- .github/workflows/check.yml
- .github/workflows/deploy-branch.yml
- .github/workflows/deploy.yml
- .github/workflows/docs.yml
- .github/workflows/pipeline.yml
- .github/workflows/security.yml
- .github/workflows/templates.yml
- settings.gradle.kts
Unfortunately, this means we lose the ability to use the configuration cache due to the AWS OIDC credentials changing each time the build runs. See gradle/gradle#20873
Hopefully they fix this in Gradle 9.x.
> PI-3161 Switch to S3 cache for Gradle

- projects/external-api-and-delius/src/dev/kotlin/uk/gov/justice/digital/hmpps/data/DataLoader.kt
- projects/external-api-and-delius/src/dev/kotlin/uk/gov/justice/digital/hmpps/data/generator/DataGenerator.kt
- projects/external-api-and-delius/src/dev/kotlin/uk/gov/justice/digital/hmpps/data/generator/PersonGenerator.kt
- projects/external-api-and-delius/src/dev/kotlin/uk/gov/justice/digital/hmpps/data/generator/RegistrationGenerator.kt
- projects/external-api-and-delius/src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/SupervisionIntegrationTest.kt
- projects/external-api-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/model/MappaDetail.kt
External API throws an exception if a MAPPA record is returned with an old level. As stated in the ndelius slack channel, Andrew Logan has stated that in this case, external api should return a null level and not throw an exception
See https://mojdt.slack.com/archives/C6C1KGRME/p1752741999193479
> HIA-834: If invalid mappa level - return null level - no exception

- .github/actions/docker-build/action.yml
So that we always get the latest security fixes for unversioned images (e.g. for monitor-cron-jobs which uses `ghcr.io/ministryofjustice/hmpps-devops-tools:nightly`).
This also checks for any changes in the built image, to determine whether there are changes to deploy.
> PI-3446 Always pull base images for Docker builds

- .github/actions/docker-build/action.yml
I think the problem was that the caches weren't scoped to the individual Docker build.  So e.g. a build for the "feature-flags" project might have been using the cache from some other project.  Hence, no caching and changes incorrectly being detected for all but one project every time.
> Attempt to fix Docker builds always detecting changes
