projects/prison-case-notes-to-probation/src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/IntegrationTest.kt
projects/prison-case-notes-to-probation/src/main/kotlin/uk/gov/justice/digital/hmpps/config/security/ServicePrincipal.kt
projects/prison-case-notes-to-probation/src/main/kotlin/uk/gov/justice/digital/hmpps/integrations/delius/audit/AuditedInteraction.kt
projects/prison-case-notes-to-probation/src/main/kotlin/uk/gov/justice/digital/hmpps/integrations/delius/audit/service/AuditedInteractionService.kt
projects/prison-case-notes-to-probation/src/main/kotlin/uk/gov/justice/digital/hmpps/integrations/delius/audit/service/AuditorAware.kt
projects/prison-case-notes-to-probation/src/main/kotlin/uk/gov/justice/digital/hmpps/integrations/delius/entity/StaffTeam.kt
projects/prison-case-notes-to-probation/src/main/resources/application.yml
projects/prison-case-notes-to-probation/src/test/kotlin/uk/gov/justice/digital/hmpps/integrations/delius/audit/AuditedInteractionTest.kt
projects/prison-case-notes-to-probation/src/test/kotlin/uk/gov/justice/digital/hmpps/integrations/delius/audit/AuditorAwareConfigurationTest.kt

post construct only works when db is pre-populated, ie not dev and integration test

reverted to using lazy block to initialise service user

---

projects/prison-case-notes-to-probation/src/dev/kotlin/uk/gov/justice/digital/hmpps/data/DataLoader.kt
projects/prison-case-notes-to-probation/src/main/kotlin/uk/gov/justice/digital/hmpps/config/DeliusConnectionProvider.kt
projects/prison-case-notes-to-probation/src/main/kotlin/uk/gov/justice/digital/hmpps/config/FeignConfig.kt
projects/prison-case-notes-to-probation/src/main/kotlin/uk/gov/justice/digital/hmpps/config/ServiceContext.kt
projects/prison-case-notes-to-probation/src/main/kotlin/uk/gov/justice/digital/hmpps/config/security/ServicePrincipal.kt
projects/prison-case-notes-to-probation/src/main/kotlin/uk/gov/justice/digital/hmpps/integrations/delius/audit/service/AuditedInteractionService.kt
projects/prison-case-notes-to-probation/src/main/kotlin/uk/gov/justice/digital/hmpps/integrations/delius/audit/service/AuditorAware.kt
projects/prison-case-notes-to-probation/src/main/kotlin/uk/gov/justice/digital/hmpps/integrations/delius/entity/Event.kt
projects/prison-case-notes-to-probation/src/main/resources/application.yml
projects/prison-case-notes-to-probation/src/test/kotlin/uk/gov/justice/digital/hmpps/config/DeliusConnectionProviderTest.kt
projects/prison-case-notes-to-probation/src/test/kotlin/uk/gov/justice/digital/hmpps/integrations/delius/audit/AuditedInteractionTest.kt
projects/prison-case-notes-to-probation/src/test/kotlin/uk/gov/justice/digital/hmpps/integrations/delius/audit/AuditorAwareConfigurationTest.kt

Fixed the issue with calling for the user id causing stack overflow issue

fix stack overflow issue with oracle setting client context

---

.github/workflows/main.yml

(to prevent unwanted deployments to Production)

Ensure end-to-end tests fail until they've been implemented

---

.github/actions/build-and-test/action.yml
.github/workflows/deploy.yml
.github/workflows/pipeline.yml

Unfortunately I can't test this before merging to main, so there may be subsequent PRs to fix any issues.

PI-359 Enable manual deployment workflow

---

.github/workflows/bootstrap.yml

The script is working now.  See this run for the pre-sentence report integration: https://github.com/ministryofjustice/hmpps-probation-integration-services/actions/runs/2847472286

PI-372 Fixed sentry project update

---

projects/prison-custody-status-to-delius/README.md
projects/prison-custody-status-to-delius/applicationinsights.json
projects/prison-custody-status-to-delius/build.gradle.kts
projects/prison-custody-status-to-delius/deploy/database/access.yml
projects/prison-custody-status-to-delius/deploy/template/task-definition.yml
projects/prison-custody-status-to-delius/deploy/values-dev.yml
projects/prison-custody-status-to-delius/deploy/values-preprod.yml
projects/prison-custody-status-to-delius/deploy/values-prod.yml
projects/prison-custody-status-to-delius/deploy/values.yml
projects/prison-custody-status-to-delius/settings.gradle.kts
projects/prison-custody-status-to-delius/src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/PrisonCustodyStatusToDeliusIntegrationTest.kt
projects/prison-custody-status-to-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/App.kt
projects/prison-custody-status-to-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/integrations/delius/audit/BusinessInteractionCode.kt
projects/prison-custody-status-to-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/listener/MessageListener.kt
projects/prison-custody-status-to-delius/src/main/resources/application.yml
projects/prison-custody-status-to-delius/src/test/kotlin/uk/gov/justice/hmpps/listener/MessageListenerTest.kt
settings.gradle.kts

Hopefully we can reference this commit later when we look to create a project initializer template.
Bootstrap run: https://github.com/ministryofjustice/hmpps-probation-integration-services/actions/runs/2866709748
Client credentials request: https://mojdt.slack.com/archives/C02S71KUBED/p1660642319818779

PI-384 Initial project setup for prison-custody-status-to-delius

---

.gitignore
.idea/codeStyles/Project.xml
.idea/codeStyles/codeStyleConfig.xml
.idea/inspectionProfiles/ktlint.xml
.idea/inspectionProfiles/profiles_settings.xml

See https://github.com/ministryofjustice/hmpps-probation-integration-services#code-formatting

Added IntelliJ codeStyles and inspectionProfiles for ktlint

---

projects/prison-custody-status-to-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/integrations/delius/recall/Recall.kt

Resolves Sentry error PRISON-CUSTODY-STATUS-TO-DELIUS-3

PI-401 Fix missing partition_area_id on Recall entity

---

projects/prison-custody-status-to-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/integrations/delius/recall/RecallService.kt
projects/prison-custody-status-to-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/integrations/delius/release/ReleaseService.kt
projects/prison-custody-status-to-delius/src/test/kotlin/uk/gov/justice/digital/hmpps/integrations/delius/recall/RecallServiceTest.kt
projects/prison-custody-status-to-delius/src/test/kotlin/uk/gov/justice/digital/hmpps/integrations/delius/release/ReleaseServiceTest.kt

These reasons are expected, but not relevant to Delius.

Ignore unused release and recall reasons

---

projects/prison-custody-status-to-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/listener/MessageListener.kt

Resolves Sentry error PRISON-CUSTODY-STATUS-TO-DELIUS-4

PI-402 Fix handling of release/recall messages with no "details" field

---

projects/person-search-index-from-delius/container/Dockerfile
projects/person-search-index-from-delius/container/logstash-full-load.conf
projects/person-search-index-from-delius/container/logstash-incremental.conf
projects/person-search-index-from-delius/container/logstash.yml
projects/person-search-index-from-delius/container/pipelines.yml
projects/person-search-index-from-delius/container/statement.sql
projects/person-search-index-from-delius/deploy/values-dev.yml
projects/person-search-index-from-delius/deploy/values-preprod.yml
projects/person-search-index-from-delius/deploy/values.yml
projects/person-search-index-from-delius/docker-compose.yml

Related PRs to add the SQS secrets to GitHub:
* https://github.com/ministryofjustice/cloud-platform-environments/pull/8548
* https://github.com/ministryofjustice/cloud-platform-environments/pull/8549
* https://github.com/ministryofjustice/cloud-platform-environments/pull/8550
I've included a `docker-compose.yml` file that you might find useful for local testing.  It doesn't test SQS connectivity, but you can switch the input in logstash-incremental.conf to "generator" which will send some fake messages.

PI-389 Incremental search indexing from SQS

---

projects/person-search-index-from-delius/config/index-config.json
projects/person-search-index-from-delius/container/statement.sql

updated template to ignore dynamic fields and updated statement to include active offender count

updated config and statement

---

projects/prison-custody-status-to-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/integrations/delius/licencecondition/category/LicenceConditionCategory.kt

Fixes PRISON-CUSTODY-STATUS-TO-DELIUS-8 (https://sentry.io/organizations/ministryofjustice/issues/3572030813/?project=6703073)

PI-412 Remove reference to soft_deleted flag on LicenceConditionCategory

---

projects/person-search-index-from-delius/deploy/values.yml

Related PR: https://github.com/ministryofjustice/hmpps-delius-core-terraform/pull/539

PI-417 Use the standby database for indexing

---

projects/person-search-index-from-delius/container/logstash-full-load.conf
projects/person-search-index-from-delius/container/logstash-incremental.conf

added validation of connections to help reduce number of connection issues

Increase Validation Frequency for OS connections

---

.github/dependabot.yml

Specify Dockerfile location for Dependabot

---

projects/pre-sentence-reports-to-delius/deploy/values.yml
projects/pre-sentence-reports-to-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/integrations/psr/PsrClient.kt
projects/pre-sentence-reports-to-delius/src/main/resources/application.yml

Fixes Sentry PRE-SENTENCE-REPORTS-TO-DELIUS-3

PI-444 Update config for client registration

---

projects/risk-assessment-scores-to-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/integrations/delius/RiskScoreService.kt
projects/risk-assessment-scores-to-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/listener/MessageListener.kt
projects/risk-assessment-scores-to-delius/src/test/kotlin/uk/gov/justice/hmpps/listener/MessageListenerTest.kt

To appease Sonar: https://sonarcloud.io/project/issues?id=ministryofjustice_hmpps-probation-integration-services&open=AYOOlMOJ1w-liGZn-ee0

Small refactor to simplify service method call

---

.github/workflows/bootstrap.yml
projects/risk-assessment-scores-to-delius/.trivyignore
projects/tier-to-delius/.trivyignore
templates/projects/message-listener-with-api-client/build.gradle.kts
templates/projects/message-listener/build.gradle.kts
templates/runConfiguration.xml

Also updated the bootstrap script to create the IntelliJ run configuration automatically.

PI-465 Added audit dependency to project templates

---

.github/workflows/bootstrap.yml
.github/workflows/deploy.yml
templates/projects/message-listener-with-api-client/deploy/values.yml
templates/projects/message-listener-with-api-client/src/main/resources/application.yml
templates/projects/message-listener-with-api-client/src/test/kotlin/uk/gov/justice/hmpps/listener/MessageListenerTest.kt
templates/projects/message-listener/deploy/values.yml
templates/projects/message-listener/src/test/kotlin/uk/gov/justice/hmpps/listener/MessageListenerTest.kt
templates/service-with-load-balancer.tf

* Add project to manual deploy workflow
* Add OAuth2 creds to values.yml
* Fix bug in load balancer Terraform code
* Update test name
* Remove use of mmercan/actions-set-secret GitHub action

Update bootstrap templates

---

doc/adr/0008-create-release-and-publish-changelog.md

PI-517 Create ADR for GitHub releases and change log publication

---

projects/approved-premises-and-delius/src/dev/kotlin/uk/gov/justice/digital/hmpps/data/DataLoader.kt
projects/approved-premises-and-delius/src/dev/kotlin/uk/gov/justice/digital/hmpps/data/generator/ProbationAreaGenerator.kt
projects/approved-premises-and-delius/src/dev/kotlin/uk/gov/justice/digital/hmpps/data/generator/TeamGenerator.kt
projects/approved-premises-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/integrations/delius/probationarea/LocalAdminUnit.kt
projects/approved-premises-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/integrations/delius/staff/Staff.kt
projects/approved-premises-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/integrations/delius/staff/StaffRepository.kt
projects/approved-premises-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/integrations/delius/team/Team.kt
projects/approved-premises-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/model/StaffResponse.kt
projects/approved-premises-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/service/StaffService.kt
projects/approved-premises-and-delius/src/test/kotlin/uk/gov/justice/digital/hmpps/service/StaffServiceTest.kt

Also rename LocalDeliveryUnit to LocalAdminUnit to match Delius

PI-525 Handle null staff grade

---

.github/actions/create-signed-pull-request/action.yml
.github/workflows/bootstrap.yml

Test PR showing commit verified: https://github.com/ministryofjustice/hmpps-probation-integration-services/pull/398

PI-524 Sign commits with the probation-integration-bot GPG key

---

libs/messaging/src/main/kotlin/uk/gov/justice/digital/hmpps/publisher/AwsNotificationPublisher.kt
libs/messaging/src/test/kotlin/uk/gov/justice/digital/hmpps/publisher/AwsNotificationPublisherTest.kt

Fixes [OFFENDER-EVENTS-AND-DELIUS-C](https://sentry.io/organizations/ministryofjustice/issues/3788879958/?project=4504094781276160)
Only required for Spring Boot 2.7, this is already fixed in the Spring Boot 3 PR.

PI-609 Fix missing topic ARN

---

.github/workflows/bootstrap.yml
templates/sqs.tf

Tested with `approved-premises-and-delius`:
PRs created:
* https://github.com/ministryofjustice/cloud-platform-environments/pull/9475
* https://github.com/ministryofjustice/cloud-platform-environments/pull/9476
* https://github.com/ministryofjustice/cloud-platform-environments/pull/9477
Issue created for manual steps:
* https://github.com/ministryofjustice/hmpps-probation-integration-services/issues/532

Update bootstrap workflow to create SQS queues in Cloud Platform

---

.github/workflows/security.yml

Also added note about suppression comment.

PI-568 Fix issues being opened and closed immediately

---

libs/audit/src/main/kotlin/uk/gov/justice/digital/hmpps/audit/service/AuditableService.kt
projects/make-recall-decisions-and-delius/src/dev/kotlin/uk/gov/justice/digital/hmpps/data/generator/PersonGenerator.kt
projects/prison-custody-status-to-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/integrations/delius/custody/Custody.kt
projects/prison-custody-status-to-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/integrations/delius/recall/RecallService.kt
projects/prison-custody-status-to-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/integrations/delius/release/ReleaseService.kt
projects/prison-custody-status-to-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/messaging/Handler.kt
projects/prison-custody-status-to-delius/src/test/kotlin/uk/gov/justice/digital/hmpps/integrations/delius/recall/RecallServiceTest.kt
projects/prison-custody-status-to-delius/src/test/kotlin/uk/gov/justice/digital/hmpps/integrations/delius/recall/TemporaryAbsenceRecallTests.kt
projects/prison-custody-status-to-delius/src/test/kotlin/uk/gov/justice/digital/hmpps/messaging/HandlerTest.kt

Resolves PRISON-CUSTODY-STATUS-TO-DELIUS-R (https://sentry.io/organizations/ministryofjustice/issues/3827485684)

PI-606 Handle null custody location change date and update Telemetry

---

.github/workflows/end-to-end-tests.yml

Also added link to GitHub Actions logs

PI-684 Fix e2e test alert firing when there are no failures

---

projects/workforce-allocations-to-delius/build.gradle.kts
projects/workforce-allocations-to-delius/deploy/values.yml
projects/workforce-allocations-to-delius/src/dev/kotlin/uk/gov/justice/digital/hmpps/data/AllocationsDataLoader.kt
projects/workforce-allocations-to-delius/src/dev/kotlin/uk/gov/justice/digital/hmpps/data/generator/ManagerGenerator.kt
projects/workforce-allocations-to-delius/src/dev/kotlin/uk/gov/justice/digital/hmpps/data/generator/OrderManagerGenerator.kt
projects/workforce-allocations-to-delius/src/dev/kotlin/uk/gov/justice/digital/hmpps/data/generator/PersonManagerGenerator.kt
projects/workforce-allocations-to-delius/src/dev/kotlin/uk/gov/justice/digital/hmpps/data/generator/RequirementManagerGenerator.kt
projects/workforce-allocations-to-delius/src/dev/kotlin/uk/gov/justice/digital/hmpps/data/generator/ResponsibleOfficerGenerator.kt
projects/workforce-allocations-to-delius/src/dev/kotlin/uk/gov/justice/digital/hmpps/data/generator/StaffGenerator.kt
projects/workforce-allocations-to-delius/src/dev/kotlin/uk/gov/justice/digital/hmpps/data/generator/UserGenerator.kt
projects/workforce-allocations-to-delius/src/dev/kotlin/uk/gov/justice/digital/hmpps/data/repository/StaffUserRepository.kt
projects/workforce-allocations-to-delius/src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/AllocationCompletedIntegrationTest.kt
projects/workforce-allocations-to-delius/src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/ChoosePractitionerIntegrationTest.kt
projects/workforce-allocations-to-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/api/model/ChoosePractitionerResponse.kt
projects/workforce-allocations-to-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/api/model/SharedModels.kt
projects/workforce-allocations-to-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/integrations/delius/provider/Staff.kt
projects/workforce-allocations-to-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/integrations/delius/user/LdapUser.kt
projects/workforce-allocations-to-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/integrations/delius/user/LdapUserRepository.kt
projects/workforce-allocations-to-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/integrations/delius/user/StaffUser.kt
projects/workforce-allocations-to-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/service/AllocationCompletedService.kt
projects/workforce-allocations-to-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/service/AllocationDemandService.kt
projects/workforce-allocations-to-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/service/LdapService.kt
projects/workforce-allocations-to-delius/src/main/resources/application.yml
projects/workforce-allocations-to-delius/src/main/resources/schema.ldif
projects/workforce-allocations-to-delius/src/test/kotlin/uk/gov/justice/digital/hmpps/service/AllocationCompletedServiceTest.kt
projects/workforce-allocations-to-delius/src/test/kotlin/uk/gov/justice/digital/hmpps/service/AllocationDemandServiceTest.kt
projects/workforce-allocations-to-delius/src/test/kotlin/uk/gov/justice/digital/hmpps/service/LdapServiceTest.kt

Related PR to enable network connectivity to the LDAP server: https://github.com/ministryofjustice/hmpps-delius-core-terraform/pull/581

PI-695 Fetch user email addresses from Delius LDAP

---

.github/workflows/access.yml

This is to prevent AWS throttling errors and DB deadlocks.
This is currently running for all projects, here: https://github.com/ministryofjustice/hmpps-probation-integration-services/actions/runs/3958458843

PI-727 Reduce concurrency in DB access workflow

---

projects/approved-premises-and-delius/src/dev/kotlin/uk/gov/justice/digital/hmpps/data/DataLoader.kt
projects/approved-premises-and-delius/src/dev/kotlin/uk/gov/justice/digital/hmpps/data/generator/CaseloadGenerator.kt
projects/approved-premises-and-delius/src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/MessagingIntegrationTest.kt
projects/approved-premises-and-delius/src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/StaffControllerIntegrationTest.kt
projects/approved-premises-and-delius/src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/TeamControllerIntegrationTest.kt
projects/approved-premises-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/controller/TeamController.kt
projects/approved-premises-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/integrations/delius/caseload/Caseload.kt
projects/approved-premises-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/integrations/delius/caseload/CaseloadRepository.kt
projects/approved-premises-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/model/TeamCodeResponse.kt
projects/approved-premises-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/service/TeamService.kt
projects/approved-premises-and-delius/src/test/kotlin/uk/gov/justice/digital/hmpps/controller/TeamControllerTest.kt
projects/approved-premises-and-delius/src/test/kotlin/uk/gov/justice/digital/hmpps/service/TeamServiceTest.kt
projects/tier-to-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/integrations/delius/management/ManagementTier.kt

See ADR discussion for more information: https://github.com/ministryofjustice/hmpps-approved-premises-api/pull/369
Also includes a minor change to tier-to-delius service to use the correct `@Immutable` annotation

PI-738 Approved premises caseload access endpoint

---

projects/person-search-index-from-delius/build.gradle.kts

To ensure we always push both tags if anything changes.

PI-896 Combine Docker push tasks

---

.github/workflows/docs.yml

This should ensure the build is successful before a project is merged to main

PI-908 Set branch when building tech-docs

---

.github/workflows/build.yml

-r is --raw-output,
-R is --raw-input.

PI-907 Fix jq arg for checking changes

---

projects/approved-premises-and-delius/.trivyignore
projects/approved-premises-and-oasys/.trivyignore
projects/create-and-vary-a-licence-and-delius/.trivyignore
projects/custody-key-dates-and-delius/.trivyignore
projects/make-recall-decisions-and-delius/.trivyignore
projects/manage-pom-cases-and-delius/.trivyignore
projects/offender-events-and-delius/.trivyignore
projects/pre-sentence-reports-to-delius/.trivyignore
projects/prison-case-notes-to-probation/.trivyignore
projects/prison-custody-status-to-delius/.trivyignore
projects/refer-and-monitor-and-delius/.trivyignore
projects/risk-assessment-scores-to-delius/.trivyignore
projects/tier-to-delius/.trivyignore
projects/unpaid-work-and-delius/.trivyignore
projects/workforce-allocations-to-delius/.trivyignore

* CVE-2023-20861 - Spring Framework vulnerable to denial of service via specially crafted SpEL expression
Suppressed as we do not process any untrusted SpEL expressions
* CVE-2023-1370 - Json-smart is vulnerable to stack exhaustion 
Suppressed as json-smart is only used internally by app insights azure-identity. Pull request created: https://github.com/microsoft/ApplicationInsights-Java/pull/2979

PI-893 Suppress vulnerability alerts for Spring Framework and Json-smart

---

projects/approved-premises-and-delius/.trivyignore
projects/approved-premises-and-oasys/.trivyignore
projects/create-and-vary-a-licence-and-delius/.trivyignore
projects/custody-key-dates-and-delius/.trivyignore
projects/make-recall-decisions-and-delius/.trivyignore
projects/manage-pom-cases-and-delius/.trivyignore
projects/offender-events-and-delius/.trivyignore
projects/pre-sentence-reports-to-delius/.trivyignore
projects/prison-case-notes-to-probation/.trivyignore
projects/prison-custody-status-to-delius/.trivyignore
projects/refer-and-monitor-and-delius/.trivyignore
projects/risk-assessment-scores-to-delius/.trivyignore
projects/tier-to-delius/.trivyignore
projects/unpaid-work-and-delius/.trivyignore
projects/workforce-allocations-to-delius/.trivyignore

(My bad, thought this one had been resolved)

PI-893 Re-add suppressions for CVE-2022-1471

---

projects/approved-premises-and-delius/.trivyignore
projects/approved-premises-and-oasys/.trivyignore
projects/court-case-and-delius/.trivyignore
projects/create-and-vary-a-licence-and-delius/.trivyignore
projects/custody-key-dates-and-delius/.trivyignore
projects/make-recall-decisions-and-delius/.trivyignore
projects/manage-pom-cases-and-delius/.trivyignore
projects/offender-events-and-delius/.trivyignore
projects/pre-sentence-reports-to-delius/.trivyignore
projects/prison-case-notes-to-probation/.trivyignore
projects/prison-custody-status-to-delius/.trivyignore
projects/refer-and-monitor-and-delius/.trivyignore
projects/risk-assessment-scores-to-delius/.trivyignore
projects/tier-to-delius/.trivyignore
projects/unpaid-work-and-delius/.trivyignore
projects/workforce-allocations-to-delius/.trivyignore

Also removed suppressions for vulnerabilities in dependencies that have been upgraded (json-smart and spring)

PI-958 Extend Trivy suppression expiry for known vulnerabilities

---

projects/make-recall-decisions-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/integrations/delius/recommendation/provider/entity/Staff.kt

(Note: this code will be removed in a subsequent PR once MRD have switched over to sending the username)

PI-577 Set staff table name

---

projects/make-recall-decisions-and-delius/deploy/values.yaml
projects/make-recall-decisions-and-delius/src/main/resources/application.yml

🤦 
Tested from a branch and finally working now.

PI-1022 Fix Feign config for auth token

---

projects/person-search-index-from-delius/container/scripts/monitor-reindexing.sh
projects/person-search-index-from-delius/deploy/templates/contact-reindex-cronjob.yml

Also print final throughput stats before shutting down

PI-1083 Increase contact index rebuild timeout

---

projects/approved-premises-and-delius/src/main/resources/application.yml
projects/court-case-and-delius/src/main/resources/application.yml
projects/create-and-vary-a-licence-and-delius/src/main/resources/application.yml
projects/custody-key-dates-and-delius/src/main/resources/application.yml
projects/effective-proposal-framework-and-delius/src/main/resources/application.yml
projects/make-recall-decisions-and-delius/src/main/resources/application.yml
projects/manage-pom-cases-and-delius/src/main/resources/application.yml
projects/offender-events-and-delius/src/main/resources/application.yml
projects/pathfinder-and-delius/src/main/resources/application.yml
projects/pre-sentence-reports-to-delius/src/main/resources/application.yml
projects/prison-case-notes-to-probation/src/main/resources/application.yml
projects/prison-custody-status-to-delius/src/main/resources/application.yml
projects/refer-and-monitor-and-delius/src/main/resources/application.yml
projects/sentence-plan-and-delius/src/main/resources/application.yml
projects/tier-to-delius/src/main/resources/application.yml
projects/unpaid-work-and-delius/src/main/resources/application.yml
projects/workforce-allocations-to-delius/src/main/resources/application.yml
templates/projects/api-client-and-server/src/main/resources/application.yml
templates/projects/api-server/src/main/resources/application.yml
templates/projects/message-listener-with-api-client-and-server/src/main/resources/application.yml
templates/projects/message-listener-with-api-client/src/main/resources/application.yml
templates/projects/message-listener/src/main/resources/application.yml

Relevant section in the README: https://github.com/ministryofjustice/hmpps-probation-integration-services#using-a-live-like-database

PI-1091 Update `delius-db` profile name to match README

---

.github/workflows/gradle.yml

also signs commits as probation-integration-bot

PI-1117 Set the correct Java version when upgrading Gradle

---

README.md

To help visitors and new devs to navigate the repo

Add project structure section to README

---

.github/workflows/docs.yml

to prevent git contention causing publish failures

PI-1058 Merge tech docs before publishing

---

.github/actions/cloud-platform-deploy/action.yml

Workaround based on: https://github.com/helm/helm/issues/8040#issuecomment-1326485199

Rollback Helm deployment when cancelling GitHub Actions workflow

---

projects/custody-key-dates-and-delius/deploy/values.yaml
projects/domain-events-and-delius/deploy/values.yaml
projects/make-recall-decisions-and-delius/deploy/values.yaml
projects/manage-pom-cases-and-delius/deploy/values.yaml
projects/offender-events-and-delius/deploy/values.yaml
projects/person-search-index-from-delius/deploy/templates/contact-reindex-cronjob.yml
projects/person-search-index-from-delius/deploy/templates/person-reindex-cronjob.yml
projects/person-search-index-from-delius/deploy/values.yaml
projects/pre-sentence-reports-to-delius/deploy/values.yaml
projects/prison-case-notes-to-probation/deploy/values.yaml
projects/prison-custody-status-to-delius/deploy/values.yaml
projects/refer-and-monitor-and-delius/deploy/values.yaml
projects/risk-assessment-scores-to-delius/deploy/values.yaml
projects/tier-to-delius/deploy/values.yaml
projects/unpaid-work-and-delius/deploy/values.yaml
projects/workforce-allocations-to-delius/deploy/values.yaml
templates/projects/message-listener-with-api-client-and-server/deploy/values.yaml
templates/projects/message-listener-with-api-client/deploy/values.yaml
templates/projects/message-listener/deploy/values.yaml

PI-1178 Fix serviceAccountName field

---

.github/workflows/suppress-trivy.yml

See https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#understanding-the-risk-of-script-injections

PI-1236 Use environment variables in Trivy suppression workflow

---

.github/actions/render-project-template/action.yml
.github/workflows/messaging.yml

Depends on https://github.com/ministryofjustice/hmpps-probation-integration-scripts/pull/15
Tested from a branch, here: https://github.com/ministryofjustice/hmpps-probation-integration-services/actions/runs/5475326437/jobs/9972354833#step:5:217

PI-1248 Added workflow for replaying domain events

---

.github/workflows/end-to-end-tests.yml

Tests now completing in under 30 mins: https://github.com/ministryofjustice/hmpps-probation-integration-services/actions/runs/5598296001

PI-1312 Increase e2e test workers from 4 to 16

---

projects/approved-premises-and-oasys/deploy/values-dev.yml

following migration to MOJ Modernisation Platform

PI-1331 Update T2 ORDS URL

---

projects/external-api-and-delius/.trivyignore
projects/resettlement-passport-and-delius/.trivyignore

missed a couple in the last PR

PI-1356 Update Trivy suppressions

---

projects/hmpps-auth-and-delius/deploy/values-dev.yml
projects/hmpps-auth-and-delius/deploy/values-preprod.yml
projects/hmpps-auth-and-delius/deploy/values-prod.yml

HMPPS Auth tokens are sent with an `iss` claim from localhost, as the tokens are issued locally.

PI-1493 Disable issuer validation

---

projects/pre-sentence-reports-to-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/integrations/delius/document/DocumentService.kt

This is an extension of https://github.com/ministryofjustice/hmpps-probation-integration-services/pull/2384

PI-1558 Update PSR extension in Alfresco

---

.github/actions/render-project-template/action.yml
doc/tech-docs/source/concepts.html.md.erb
doc/tech-docs/source/guides.html.md.erb
doc/tech-docs/source/index.html.md.erb
doc/tech-docs/source/services.html.md.erb
doc/tech-docs/source/support.html.md.erb

- Initial attempt at starting an overview of the concepts we use in the integration services
- Also classify the integration services into service areas

Document Probation System Concepts 

---

libs/commons/src/main/kotlin/uk/gov/justice/digital/hmpps/ldap/LdapTemplateExtensions.kt
libs/commons/src/test/kotlin/uk/gov/justice/digital/hmpps/ldap/LdapTemplateExtensionsTest.kt
projects/dps-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/service/DocumentService.kt

Fixes https://ministryofjustice.sentry.io/issues/4662638594

PI-1683 Use dn for aliasedObjectName

---

projects/dps-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/service/DocumentService.kt

This potentially introduces an intermittent ConcurrentModificationException during integration tests, but fixes an intermittent NullPointerException at runtime.
Fixes https://ministryofjustice.sentry.io/issues/4662952312

PI-1684 Revert DPS streaming headers change

---

projects/hdc-licences-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/entity/ProbationArea.kt

SQL restriction is already applied on the repository method

PI-1713 Handle teams linked to non-selectable providers

---

.github/workflows/schema-spy.yml
tools/schema-spy/run.sh

Successful in 7m 28s: https://github.com/ministryofjustice/hmpps-probation-integration-services/actions/runs/7221872066/job/19677753740
Report available at: https://ministryofjustice.github.io/hmpps-probation-integration-services/schema-spy-report/

PI-1648 Disable vizjs in SchemaSpy report

---

.github/workflows/readonly.yml

* add Slack notifications
* fully shutdown services in the Test environment where there is no standby database
* add exception for HMPPS Auth ingress to continue allowing logins as the service is read-only anyway

PI-1663 Update readonly workflow

---

.github/workflows/reports.yml

Example: https://mojdt.slack.com/archives/C035YK9FFK4/p1704293093735869

PI-1764 Generate weekly report to Slack with failed MaW allocations

---

projects/person-search-index-from-delius/container/pipelines/contact/logstash-incremental.conf
projects/person-search-index-from-delius/container/pipelines/person/logstash-incremental.conf

Also added log to stdout on failure

PI-1761 Fix indexing of deleted contacts

---

.github/actions/cloud-platform-deploy/action.yml
.github/actions/get-build-info/action.yml
.github/dependabot.yml
build.gradle.kts
libs/commons/src/main/kotlin/uk/gov/justice/digital/hmpps/config/BuildInfoConfig.kt
libs/commons/src/test/kotlin/uk/gov/justice/digital/hmpps/config/BuildInfoConfigTest.kt

Example: https://hmpps-auth-and-delius-dev.hmpps.service.justice.gov.uk/info
```json
{
"git": {
"branch": "PI-1748-build-info",
"commit": {
"id": "9fe8ca9",
"time": "2024-01-10T14:37:38Z"
}
},
"build": {
"artifact": "hmpps-auth-and-delius",
"name": "hmpps-auth-and-delius",
"time": "2024-01-10T14:45:59.284Z",
"version": "2024-01-10.2109.9fe8ca9",
"group": "uk.gov.justice.digital"
}
}
```

PI-1748 Add build info from environment variables

---

.github/workflows/readonly.yml

to account for intermittent failures from MOJ Cloud Platform

PI-1783 Retry ingress patching when enabling read-only mode

---

.github/actions/create-signed-pull-request/action.yml
.github/workflows/bootstrap.yml

Fix PR signing for e2e repo in bootstrap

---

projects/create-and-vary-a-licence-and-delius/src/dev/kotlin/uk/gov/justice/digital/hmpps/data/DataLoader.kt
projects/create-and-vary-a-licence-and-delius/src/dev/kotlin/uk/gov/justice/digital/hmpps/data/generator/OfficeLocationGenerator.kt
projects/create-and-vary-a-licence-and-delius/src/dev/kotlin/uk/gov/justice/digital/hmpps/data/generator/PersonGenerator.kt
projects/create-and-vary-a-licence-and-delius/src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/IntegrationTest.kt
projects/create-and-vary-a-licence-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/api/model/Manager.kt
projects/create-and-vary-a-licence-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/integrations/delius/manager/entity/PersonManager.kt
projects/create-and-vary-a-licence-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/integrations/delius/provider/entity/Provider.kt
projects/create-and-vary-a-licence-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/service/ManagerService.kt
projects/create-and-vary-a-licence-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/service/OfficeAddressService.kt
projects/create-and-vary-a-licence-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/service/StaffService.kt
projects/create-and-vary-a-licence-and-delius/src/test/kotlin/uk/gov/justice/digital/hmpps/service/StaffServiceTest.kt

Ive only put this in the team object when the team is as part of the manager endpoint

PI-1834: Add team addresses to responsible com endpoint

---

.github/workflows/readonly.yml

Separates the workflow into 3 separate jobs, and uses the matrix strategy to create a separate run per-project

PI-1790 Toggle read-only mode in parallel by service

---

.github/actions/analyse/action.yml
.github/actions/get-build-info/action.yml
.github/workflows/build.yml
.github/workflows/docs.yml
.github/workflows/security.yml
.github/workflows/templates.yml

The gradle/gradle-build-action@v2 action is deprecated

PI-1818 Switch to gradle/actions/setup-gradle@v3

---

.github/actions/cloud-platform-deploy/action.yml
.github/actions/get-build-info/action.yml

Examples of retried deployments:
* https://github.com/ministryofjustice/hmpps-probation-integration-services/actions/runs/7742464276/job/21111822630#step:7:507
* https://github.com/ministryofjustice/hmpps-probation-integration-services/actions/runs/7742464276/job/21111813425#step:7:518

PI-1853 Retry Helm upgrade on "context deadline exceeded" error

---

projects/prison-identifier-and-delius/src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/MergeIntegrationTest.kt
projects/prison-identifier-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/messaging/Converter.kt
projects/prison-identifier-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/messaging/Handler.kt
projects/prison-identifier-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/messaging/OffenderEvent.kt

To catch cases where the sentence is added to Delius shortly after NOMIS

PI-2062 Use SENTENCE_CHANGED offender event

---

projects/refer-and-monitor-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/integrations/delius/referral/RequirementRepository.kt
projects/refer-and-monitor-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/integrations/delius/referral/entity/Requirement.kt
projects/refer-and-monitor-and-delius/tech-docs/diag/randm-and-delius-workflow-appointment-feedback.d2
projects/refer-and-monitor-and-delius/tech-docs/source/img/randm-and-delius-appointment-context-map.svg
projects/refer-and-monitor-and-delius/tech-docs/source/img/randm-and-delius-dependencies-context-map.svg
projects/refer-and-monitor-and-delius/tech-docs/source/img/randm-and-delius-referral-context-map.svg
projects/refer-and-monitor-and-delius/tech-docs/source/img/randm-and-delius-workflow-action-plan.svg
projects/refer-and-monitor-and-delius/tech-docs/source/img/randm-and-delius-workflow-appointment-feedback.svg
projects/refer-and-monitor-and-delius/tech-docs/source/img/randm-and-delius-workflow-appointment-reschedule.svg
projects/refer-and-monitor-and-delius/tech-docs/source/img/randm-and-delius-workflow-create-crs-referral.svg
projects/refer-and-monitor-and-delius/tech-docs/source/img/randm-and-delius-workflow-end-crs-referral.svg

Previously, when session feedback was received for an appointment linked to a terminated requirement, then the RAR count would not be re-calculated. However, session feedback can still be recorded after the termination, and we should still update the RAR count in this case.

PI-2174 Recalculate RAR count for inactive requirements

---

projects/prison-custody-status-to-delius/src/dev/kotlin/uk/gov/justice/digital/hmpps/data/generator/EventGenerator.kt
projects/prison-custody-status-to-delius/src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/PcstdIntegrationTest.kt
projects/prison-custody-status-to-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/integrations/delius/custody/entity/Custody.kt
projects/prison-custody-status-to-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/messaging/actions/UpdateLocationAction.kt

To avoid validation issues in the Delius UI.

PI-2198 Remove timestamp from custody location changed date

---

.github/actions/app-insights-to-slack/action.yml
.github/workflows/reports.yml
projects/manage-offences-and-delius/src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/IntegrationTest.kt
projects/manage-offences-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/client/ManageOffencesClient.kt
projects/manage-offences-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/entity/ReferenceOffence.kt
projects/manage-offences-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/messaging/Handler.kt
projects/manage-offences-and-delius/src/test/kotlin/uk/gov/justice/digital/hmpps/messaging/HandlerTest.kt

Also refactors the Handler class to make the ReferenceOffence update consistent with the DetailedOffence update.

PI-2192 Fix nulls appearing in offences report

---

projects/court-case-and-delius/src/dev/kotlin/uk/gov/justice/digital/hmpps/data/generator/PersonGenerator.kt
projects/court-case-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/integrations/delius/person/entity/PersonManager.kt
projects/court-case-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/integrations/delius/service/OffenderService.kt

PI-2218 Remove start date column

---

projects/refer-and-monitor-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/service/ContractTypeNsiType.kt

Add new contract type for FBD in Oldham, 
missed in initial client specification / request

Add new contract type for FBD in Oldham

---

projects/manage-offences-and-delius/src/dev/kotlin/uk/gov/justice/digital/hmpps/data/DataLoader.kt
projects/manage-offences-and-delius/src/dev/kotlin/uk/gov/justice/digital/hmpps/data/generator/DataGenerator.kt
projects/manage-offences-and-delius/src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/IntegrationTest.kt
projects/manage-offences-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/messaging/Handler.kt
projects/manage-offences-and-delius/src/test/kotlin/uk/gov/justice/digital/hmpps/messaging/HandlerTest.kt

Also appends the Home Office code to the offence description

PI-2242 Move updates of existing offences behind a feature flag

---

.github/workflows/bootstrap.yml

Example: https://ministryofjustice.sentry.io/alerts/rules/details/256457/

PI-2200 Add Sentry alert for high throughput

---

projects/manage-offences-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/messaging/Handler.kt

Now takes into account new offences where we already have a r_detailed_offence record.

PI-2304 Fix isNew check on offence code creation

---

projects/assessment-summary-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/integrations/delius/court/entity/Court.kt

Note: there are no duplicate court codes in prod

PI-2328 Handle duplicate court codes in the Delius test environment

---

projects/manage-offences-and-delius/src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/IntegrationTest.kt
projects/manage-offences-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/messaging/Handler.kt
projects/manage-offences-and-delius/src/test/kotlin/uk/gov/justice/digital/hmpps/messaging/HandlerTest.kt
projects/opd-and-delius/src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/OpdIntegrationTest.kt
projects/opd-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/messaging/Handler.kt
projects/prison-case-notes-to-probation/src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/CaseNotesIntegrationTest.kt
projects/prison-case-notes-to-probation/src/main/kotlin/uk/gov/justice/digital/hmpps/messaging/Handler.kt
projects/prison-case-notes-to-probation/src/test/kotlin/uk/gov/justice/digital/hmpps/integrations/delius/service/CaseNoteRelatedServiceTest.kt
projects/prison-case-notes-to-probation/src/test/kotlin/uk/gov/justice/digital/hmpps/integrations/delius/service/DeliusServiceTest.kt
projects/prison-case-notes-to-probation/src/test/kotlin/uk/gov/justice/digital/hmpps/messaging/HandlerTest.kt
projects/prison-custody-status-to-delius/src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/PcstdIntegrationTest.kt
projects/prison-custody-status-to-delius/src/main/resources/application-prisoner-movement.yml

Also removes unused update offence functionality (PI-2231)

PI-2294 Remove old feature flags

---

projects/feature-flags/deploy/grafana/flipt-evaluations.json

Sum metrics across pods + stack results

PI-2335 Update Grafana dashboard for flipt

---

libs/messaging/src/main/kotlin/uk/gov/justice/digital/hmpps/listener/AwsNotificationListener.kt
libs/messaging/src/main/kotlin/uk/gov/justice/digital/hmpps/publisher/QueuePublisher.kt
libs/messaging/src/main/kotlin/uk/gov/justice/digital/hmpps/publisher/TopicPublisher.kt
libs/messaging/src/main/kotlin/uk/gov/justice/digital/hmpps/telemetry/TelemetryMessagingExtensions.kt
projects/domain-events-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/service/DomainEventService.kt
projects/offender-events-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/integrations/delius/offender/OffenderDeltaService.kt

Replaces:
* `TopicPublisher.publish` with `PUBLISH $eventType`
* `AwsNotificationListener.receive` with `RECEIVE $eventType`

PI-2342 Improve Telemetry for message publishing

---

projects/prison-custody-status-to-delius/src/main/resources/application-prisoner-movement.yml

Also combined a few configs to tidy things up

PI-2392 Do not create a release for repatriated cases

---

projects/person-search-index-from-delius/container/pipelines/contact/index/contact-search-template.yml

DST-17601 Fix typo in synonym list + tidy up

---

projects/person-search-index-from-delius/container/pipelines/contact/index/contact-search-template.yml

Fixes "court" not matching "crown court"

DST-17607 Separate one-way synonyms into their own filter

---

.github/CODEOWNERS
.github/actions/format-code/action.yml
gradle/wrapper/gradle-wrapper.properties
tools/ingress-testing/api-client/gradle/wrapper/gradle-wrapper.properties

Workaround for GitHub apps not working in CODEOWNERS - see https://github.com/orgs/community/discussions/23064

PI-2410 Exclude files from CODEOWNERS

---

.github/workflows/gradle.yml

Details in https://github.com/dsanders11/github-app-commit-action/pull/20

PI-2302 Fix Gradle wrapper upgrade after switch to GitHub app

---

projects/approved-premises-and-delius/src/dev/kotlin/uk/gov/justice/digital/hmpps/data/DataLoader.kt
projects/approved-premises-and-delius/src/dev/kotlin/uk/gov/justice/digital/hmpps/data/generator/StaffGenerator.kt
projects/approved-premises-and-delius/src/dev/kotlin/uk/gov/justice/digital/hmpps/data/generator/TeamGenerator.kt

This commit updates the region for the ‘Jim Snow’ test user to align with test data used by the approved-premises API team.

APS-1225 Update ap-and-delius test user region

---

projects/approved-premises-and-delius/src/dev/kotlin/uk/gov/justice/digital/hmpps/data/DataLoader.kt
projects/approved-premises-and-delius/src/dev/kotlin/uk/gov/justice/digital/hmpps/data/generator/ProbationCaseGenerator.kt
projects/approved-premises-and-delius/src/dev/kotlin/uk/gov/justice/digital/hmpps/data/generator/ReferenceDataGenerator.kt
projects/approved-premises-and-delius/src/dev/kotlin/uk/gov/justice/digital/hmpps/data/generator/StaffGenerator.kt
projects/approved-premises-and-delius/src/dev/resources/schema.ldif

This commit adds a Female Probation Case and additional Staff Member to support testing of the Women’s Estate Solution

Add Approved Premises Women's Estate Test Data

---

projects/make-recall-decisions-and-delius/README.md
projects/make-recall-decisions-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/messaging/Handler.kt

PI-2525 Update recall domain events docs

---

projects/person-search-index-from-delius/deploy/templates/contact-index-deletion-cronjob.yml

PI-2532 Daily job to delete semantic search indices

---

projects/person-search-index-from-delius/deploy/templates/contact-reindex-cronjob.yml
projects/person-search-index-from-delius/deploy/templates/person-reindex-cronjob.yml
projects/person-search-index-from-delius/deploy/values.yaml

Before:
```
JVM bootstrap flags: [-XX:MaxRAMPercentage=75.0, -Xms1g, -Xmx1g, ...
```
After:
```
JVM bootstrap flags: [-Xms1g, -Xmx1g, ..., -Xms3g, -Xmx3g, ...
```

PI-2573 Use LS_JAVA_OPTS instead of JDK_JAVA_OPTIONS in Logstash

---

projects/redrive-dead-letter-queues/container/Dockerfile
projects/redrive-dead-letter-queues/container/scripts/notify.sh
projects/redrive-dead-letter-queues/container/scripts/redrive.sh
projects/redrive-dead-letter-queues/container/scripts/startup.sh
projects/redrive-dead-letter-queues/deploy/templates/redrive.yml
projects/redrive-dead-letter-queues/deploy/values.yaml
script/start-service-pod.sh

Related: https://github.com/ministryofjustice/cloud-platform-environments/pull/26790
Tested here: https://mojdt.slack.com/archives/C033HPR0W91/p1728660056559409

PI-2582 Script for notifying Slack of DLQ messages

---

.github/workflows/build.yml
.github/workflows/deploy.yml

Also add version to Sentry release

PI-2591 Retry push to GitHub Packages

---

projects/person-search-index-from-delius/container/scripts/deploy-semantic-model.sh
projects/person-search-index-from-delius/container/scripts/startup.sh

https://ministryofjustice.sentry.io/issues/3995677633/events/latest/?alert_rule_id=12101843&alert_type=issue&notification_uuid=34edacdf-14e7-4362-ae5a-a53ed963518c&project=6709320&referrer=latest-event

PI-2580 Ignore 409 conflict when deploying OpenSearch model

---

projects/common-platform-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/messaging/CommonPlatformHearing.kt

PI-2575 change data structure to match input hearing messages for nullable fields

PI-2575 Update data structure of hearing for nullable fields

---

projects/appointment-reminders-and-delius/src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/IntegrationTest.kt
projects/appointment-reminders-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/controller/ApiController.kt
projects/appointment-reminders-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/model/UnpaidWorkAppointment.kt
projects/appointment-reminders-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/repository/UpwAppointmentRepository.kt

Filters out end-dated personal circumstances, LAO cases, and custodial cases

PI-2543 Update UPW report filters

---

projects/common-platform-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/messaging/CommonPlatformHearing.kt

- Allow hearings' case status and master defendant id fields to be null

PI-2575 Case status and master defendant id fields nullable

---

.github/workflows/security.yml

with fallback to GHCR, should help mitigate rate-limiting issues

PI-2613 Add ECR repository for Trivy scanning

---

.github/actions/analyse/action.yml
.github/actions/cloud-platform-deploy/action.yml
.github/actions/get-build-info/action.yml
.github/actions/setup-gradle/action.yml
.github/workflows/build.yml
.github/workflows/check.yml
.github/workflows/deploy.yml
.github/workflows/docs.yml
.github/workflows/pipeline.yml
.github/workflows/security.yml
.github/workflows/templates.yml
gradle.properties

This should shave another 20-30 seconds off build times

PI-2624 Enable Gradle configuration cache

---

projects/appointment-reminders-and-delius/deploy/templates/unpaid-work-appointment-reminders-cronjob.yml
projects/appointment-reminders-and-delius/deploy/values-dev.yml
projects/appointment-reminders-and-delius/deploy/values-preprod.yml
projects/appointment-reminders-and-delius/deploy/values-prod.yml
projects/appointment-reminders-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/cronjob/UpwAppointmentRemindersJob.kt
projects/appointment-reminders-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/service/UnpaidWorkAppointmentsService.kt

Also remove unused dryRun flag.

PI-2657 Set UPW reminder schedule to 10am

---

projects/assessment-summary-and-delius/src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/IntegrationTest.kt
projects/assessment-summary-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/integrations/delius/person/entity/Registration.kt
projects/assessment-summary-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/service/RiskService.kt

Also add note about risk level change

PI-2708 Add review contact notes to review notes

---

projects/assessment-summary-and-delius/src/dev/kotlin/uk/gov/justice/digital/hmpps/data/DataLoader.kt
projects/assessment-summary-and-delius/src/dev/kotlin/uk/gov/justice/digital/hmpps/data/generator/PersonGenerator.kt
projects/assessment-summary-and-delius/src/dev/resources/simulations/__files/A000012-no-existing-level.json
projects/assessment-summary-and-delius/src/dev/resources/simulations/mappings/oasys-mappings.json
projects/assessment-summary-and-delius/src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/IntegrationTest.kt
projects/assessment-summary-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/integrations/delius/person/entity/Registration.kt
projects/assessment-summary-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/service/RiskService.kt

instead of replacing it with a new registration

PI-2703 Add level to existing registrations in-place

---

projects/court-case-and-delius/src/main/resources/application.yml

Due to failure generating tech-docs: https://github.com/ministryofjustice/hmpps-probation-integration-services/actions/runs/12761754164

Pin OpenAPI version to 3.0 for court-case-and-delius

---

libs/dev-tools/src/main/kotlin/uk/gov/justice/digital/hmpps/test/CustomMatchers.kt
projects/approved-premises-and-delius/src/dev/kotlin/uk/gov/justice/digital/hmpps/data/generator/ReferenceDataGenerator.kt
projects/approved-premises-and-delius/src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/MessagingIntegrationTest.kt
projects/approved-premises-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/integrations/delius/nonstatutoryintervention/entity/Nsi.kt
projects/approved-premises-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/integrations/delius/nonstatutoryintervention/entity/NsiStatus.kt
projects/approved-premises-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/integrations/delius/nonstatutoryintervention/entity/NsiType.kt
projects/approved-premises-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/integrations/delius/referencedata/ReferenceDataRepository.kt
projects/approved-premises-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/service/NsiService.kt
projects/approved-premises-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/service/ReferralService.kt
projects/approved-premises-and-delius/src/test/kotlin/uk/gov/justice/digital/hmpps/service/ApprovedPremisesServiceTest.kt

and close it down on departure.

PI-2714 Add Rehabilitative Activities NSI on CAS1 arrival

---

projects/assessment-summary-and-delius/README.md
projects/assessment-summary-and-delius/tech-docs/diag/assessment-summary-assessment-submitted.d2
projects/assessment-summary-and-delius/tech-docs/source/img/assessment-summary-assessment-submitted.svg

Correct the name of the assessment summary and Delius queue name and event type filter.

Correct the assessment summary event type in the docs

---

projects/common-platform-and-delius/src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/IntegrationTest.kt
projects/common-platform-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/service/PersonService.kt

- Added Transactional annotation to rollback database transactions if an error occurs in insertPerson / insertAddress
- Added integration test

PI-2794 - Cases being created without offender_manager

---

.github/actions/render-project-template/action.yml
.github/workflows/deploy.yml

Note: it's also possible to deploy from a branch (including main) using https://github.com/ministryofjustice/hmpps-probation-integration-services/actions/workflows/deploy-branch.yml

PI-2827 Re-enable manual version deployments

---

.github/workflows/build.yml
tools/github-browser.html

Example:
* run: https://github.com/ministryofjustice/hmpps-probation-integration-services/actions/runs/13413359305
* report: https://ministryofjustice.github.io/hmpps-probation-integration-services/test-reports/PI-2758-test-reports/2025-02-19/feb190abd174e62cb206e214057649c020b9317f/13413359305/1/appointment-reminders-and-delius/

PI-2758 Publish test reports to GitHub Pages

---

libs/commons/src/main/kotlin/uk/gov/justice/digital/hmpps/job/CronJobHelper.kt
libs/commons/src/main/kotlin/uk/gov/justice/digital/hmpps/logging/LazyLogger.kt
libs/commons/src/main/kotlin/uk/gov/justice/digital/hmpps/logging/Logger.kt
libs/commons/src/test/kotlin/uk/gov/justice/digital/hmpps/job/CronJobHelperTest.kt
projects/appointment-reminders-and-delius/deploy/values-dev.yml
projects/appointment-reminders-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/cronjob/UpwAppointmentRemindersJob.kt
projects/appointment-reminders-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/service/UnpaidWorkAppointmentsService.kt
projects/custody-key-dates-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/cronjob/BulkUpdateRunner.kt
projects/manage-pom-cases-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/cronjob/BulkUpdateRunner.kt
projects/prison-identifier-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/cronjob/BulkUpdateRunner.kt

Also updates the Wales UPW cron job to run during the day in dev.

PI-2851 Improve Telemetry for cron jobs + fix hanging jobs

---

.github/workflows/security.yml

PI-2846 Switch to HMPPS Veracode keys

---

libs/oauth-client/src/main/kotlin/uk/gov/justice/digital/hmpps/config/security/HmppsAuthClientConfig.kt
projects/assessment-summary-and-delius/src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/IntegrationTest.kt
projects/assessment-summary-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/integrations/oasys/OrdsClient.kt
projects/assessment-summary-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/messaging/Handler.kt
projects/prison-identifier-and-delius/src/dev/resources/messages/prisoner-status-changed-no-booking.json
projects/prison-identifier-and-delius/src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/ProbationMatchingIntegrationTest.kt
projects/prison-identifier-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/client/PrisonApiClient.kt
projects/prison-identifier-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/service/ProbationMatchingService.kt

Also update Assessment Summary to correctly handle 404 from OASys

PI-2868 Handle 404 from Prison API

---

projects/person-search-index-from-delius/container/pipelines/contact/index/index-template-semantic.yml
projects/person-search-index-from-delius/container/pipelines/contact/index/ingest-pipeline.tpl.json

Also escape commas in updated synonym list

PI-2876 Remove date, type, outcome, description from semantic text chunks

---

projects/person-search-index-from-delius/container/pipelines/contact/index/search-pipeline.tpl.json

Increasing weight for keyword/literal query results

PI-2911 Switch back to min-max with weights

---

projects/person-search-index-from-delius/container/Dockerfile
projects/person-search-index-from-delius/container/pipelines/person/logstash-full-load.conf
projects/person-search-index-from-delius/container/pipelines/person/logstash-incremental.conf

To improve query parsing performance

PI-2945 Use bind variables for person search indexer SQL

---

projects/person-search-index-from-delius/container/pipelines/person/statement.sql

to avoid sub-optimal query plan when querying additional_identifier

Update SQL for person search indexer

---

projects/approved-premises-and-delius/deploy/values-dev.yml
projects/prisoner-profile-and-delius/deploy/values-dev.yml

Temporarily remove issuer validation for CAS + Prisoner Profile in dev

---

projects/prison-case-notes-to-probation/src/main/kotlin/uk/gov/justice/digital/hmpps/integrations/prison/PrisonCaseNoteFilters.kt
projects/prison-case-notes-to-probation/src/test/kotlin/uk/gov/justice/digital/hmpps/messaging/PersonCaseNoteTest.kt

ZZGHI is the ghost holding establishment

PI-3009 Fix ignoring case notes that reference ZZGHI

---

.github/actions/cloud-platform-deploy/action.yml
.github/actions/docker-build/action.yml
.github/actions/get-build-info/action.yml
.github/actions/gradle-build/action.yml
.github/workflows/check.yml
.github/workflows/deploy.yml
.github/workflows/pipeline.yml
settings.gradle.kts

also, replace deprecated Sentry parameter and fix build scan publishing

PI-3161 Add checks permission for analyse job

---

projects/risk-assessment-scores-to-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/integrations/delius/RiskAssessmentService.kt

Fixes [RISK-ASSESSMENT-SCORES-TO-DELIUS-1H](https://ministryofjustice.sentry.io/issues/6702131334)

PI-3176 Ignore deleted CRNs for OGRS messages

---

projects/appointment-reminders-and-delius/src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/IntegrationTest.kt
projects/appointment-reminders-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/repository/UpwAppointmentRepository.kt

Fixes [APPOINTMENT-REMINDERS-AND-DELIUS-4](https://ministryofjustice.sentry.io/issues/6731163749) and [APPOINTMENT-REMINDERS-AND-DELIUS-5](https://ministryofjustice.sentry.io/issues/6731237211).
Tested: https://github.com/ministryofjustice/hmpps-probation-integration-e2e-tests/actions/runs/16113490796

PI-3243 Fix handling of excluded provider codes list

---

projects/approved-premises-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/integrations/delius/approvedpremises/referral/entity/Referral.kt
projects/approved-premises-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/service/ReferralService.kt

Fixes [APPROVED-PREMISES-AND-DELIUS-5R](https://ministryofjustice.sentry.io/issues/6747831713), [APPROVED-PREMISES-AND-DELIUS-5T](https://ministryofjustice.sentry.io/issues/6752749677), [APPROVED-PREMISES-AND-DELIUS-5S](https://ministryofjustice.sentry.io/issues/6750494416), [APPROVED-PREMISES-AND-DELIUS-5Q](https://ministryofjustice.sentry.io/issues/6747713238)

PI-3302 Handle null staff / team IDs

---

projects/common-platform-and-delius/src/test/kotlin/uk/gov/justice/digital/hmpps/messaging/EventServiceTest.kt
projects/manage-pom-cases-and-delius/src/test/kotlin/uk/gov/justice/digital/hmpps/services/messaging/HandlerTest.kt
projects/manage-supervision-and-delius/src/test/kotlin/uk/gov/justice/digital/hmpps/api/controller/UserAccessControllerTest.kt
projects/prison-identifier-and-delius/src/test/kotlin/uk/gov/justice/digital/hmpps/utils/SearchHelperTest.kt

Fix package names for test files

---

libs/commons/src/main/kotlin/uk/gov/justice/digital/hmpps/telemetry/TelemetryService.kt
libs/document-management/src/main/kotlin/uk/gov/justice/digital/hmpps/alfresco/AlfrescoClient.kt
projects/approved-premises-and-delius/src/dev/kotlin/uk/gov/justice/digital/hmpps/data/generator/DocumentGenerator.kt
projects/approved-premises-and-delius/src/dev/resources/simulations/mappings/alfresco.json
projects/approved-premises-and-delius/src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/DocIntegrationTest.kt
projects/court-case-and-delius/src/dev/kotlin/uk/gov/justice/digital/hmpps/data/DataLoader.kt
projects/court-case-and-delius/src/dev/kotlin/uk/gov/justice/digital/hmpps/data/generator/DocumentEntityGenerator.kt
projects/court-case-and-delius/src/dev/resources/simulations/mappings/get-document.json
projects/court-case-and-delius/src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/DocumentsIntegrationTest.kt
projects/dps-and-delius/src/dev/kotlin/uk/gov/justice/digital/hmpps/data/generator/DocumentGenerator.kt
projects/dps-and-delius/src/dev/resources/simulations/mappings/alfresco.json
projects/dps-and-delius/src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/IntegrationTest.kt
projects/hmpps-auth-and-delius/src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/AuthenticationIntegrationTest.kt
projects/hmpps-auth-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/controller/AuthenticationController.kt
projects/make-recall-decisions-and-delius/src/dev/kotlin/uk/gov/justice/digital/hmpps/data/generator/ContactGenerator.kt
projects/make-recall-decisions-and-delius/src/dev/kotlin/uk/gov/justice/digital/hmpps/data/generator/DocumentGenerator.kt
projects/make-recall-decisions-and-delius/src/dev/resources/simulations/mappings/alfresco.json
projects/make-recall-decisions-and-delius/src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/DocumentIntegrationTest.kt
projects/manage-supervision-and-delius/src/dev/kotlin/uk/gov/justice/digital/hmpps/data/generator/personalDetails/PersonDetailsGenerator.kt
projects/manage-supervision-and-delius/src/dev/resources/simulations/mappings/alfresco.json
projects/manage-supervision-and-delius/src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/PersonalDetailsIntegrationTest.kt
projects/manage-supervision-and-delius/src/test/kotlin/uk/gov/justice/digital/hmpps/api/controller/PersonalDetailsControllerTest.kt
projects/manage-supervision-and-delius/src/test/kotlin/uk/gov/justice/digital/hmpps/service/PersonalDetailsServiceTest.kt
projects/manage-supervision-and-delius/src/test/kotlin/uk/gov/justice/digital/hmpps/service/SentenceServiceTest.kt
projects/prisoner-profile-and-delius/src/dev/kotlin/uk/gov/justice/digital/hmpps/data/generator/DocumentGenerator.kt
projects/prisoner-profile-and-delius/src/dev/resources/simulations/mappings/alfresco.json
projects/prisoner-profile-and-delius/src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/PrisonerDocumentsIntTest.kt

* Validate that the user-provided document id is a UUID
* Sanitise HMPPS Auth error response
* Sanitise logs in TelemetryService

PI-3256 Fix Veracode issues

---

libs/commons/src/main/kotlin/uk/gov/justice/digital/hmpps/telemetry/TelemetryService.kt

Veracode only supports specific methods for cleansing, see https://docs.veracode.com/r/Supported_Java_Cleansing_Functions

PI-3256 More log sanitisation

---

projects/approved-premises-and-delius/deploy/database/access.yml

Fixes [APPROVED-PREMISES-AND-DELIUS-5V](https://ministryofjustice.sentry.io/issues/6764942441)

PI-3308 Add permissions to trigger caseload rebuild

---

projects/accredited-programmes-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/entity/registration/Registration.kt
projects/accredited-programmes-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/model/Registration.kt
projects/accredited-programmes-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/service/CaseDetailService.kt

Fixes [ACCREDITED-PROGRAMMES-AND-DELIUS-2](https://ministryofjustice.sentry.io/issues/6805884170)

PI-3363 Handle null registration category

---

projects/person-search-index-from-delius/container/pipelines/contact-semantic/index/index-template-semantic.yml
projects/person-search-index-from-delius/container/pipelines/contact-semantic/index/ingest-pipeline.tpl.json

To test whether this improves performance by leveraging efficient k-NN filtering

PI-3476 Duplicate CRN into nested embedding field
